/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AssessmentIndexRouteImport } from './routes/assessment/index'
import { Route as AuthProfileRouteImport } from './routes/auth/profile'
import { Route as AssessmentResultsRouteImport } from './routes/assessment/results'
import { Route as AssessmentQuizRouteImport } from './routes/assessment/quiz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIndexRoute = AssessmentIndexRouteImport.update({
  id: '/assessment/',
  path: '/assessment/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/auth/profile',
  path: '/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentResultsRoute = AssessmentResultsRouteImport.update({
  id: '/assessment/results',
  path: '/assessment/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentQuizRoute = AssessmentQuizRouteImport.update({
  id: '/assessment/quiz',
  path: '/assessment/quiz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment/quiz': typeof AssessmentQuizRoute
  '/assessment/results': typeof AssessmentResultsRoute
  '/auth/profile': typeof AuthProfileRoute
  '/assessment': typeof AssessmentIndexRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment/quiz': typeof AssessmentQuizRoute
  '/assessment/results': typeof AssessmentResultsRoute
  '/auth/profile': typeof AuthProfileRoute
  '/assessment': typeof AssessmentIndexRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment/quiz': typeof AssessmentQuizRoute
  '/assessment/results': typeof AssessmentResultsRoute
  '/auth/profile': typeof AuthProfileRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment/quiz'
    | '/assessment/results'
    | '/auth/profile'
    | '/assessment'
    | '/auth'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment/quiz'
    | '/assessment/results'
    | '/auth/profile'
    | '/assessment'
    | '/auth'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/assessment/quiz'
    | '/assessment/results'
    | '/auth/profile'
    | '/assessment/'
    | '/auth/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentQuizRoute: typeof AssessmentQuizRoute
  AssessmentResultsRoute: typeof AssessmentResultsRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AssessmentIndexRoute: typeof AssessmentIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/': {
      id: '/assessment/'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/profile': {
      id: '/auth/profile'
      path: '/auth/profile'
      fullPath: '/auth/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/results': {
      id: '/assessment/results'
      path: '/assessment/results'
      fullPath: '/assessment/results'
      preLoaderRoute: typeof AssessmentResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/quiz': {
      id: '/assessment/quiz'
      path: '/assessment/quiz'
      fullPath: '/assessment/quiz'
      preLoaderRoute: typeof AssessmentQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentQuizRoute: AssessmentQuizRoute,
  AssessmentResultsRoute: AssessmentResultsRoute,
  AuthProfileRoute: AuthProfileRoute,
  AssessmentIndexRoute: AssessmentIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
