-- Create Exams table (Parent)
create table public.exams (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text null,
  exam_format text null, -- New field
  website_url text null, -- New field
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Timeline Events table (Child)
create table public.timeline_events (
  id bigint generated by default as identity primary key,
  exam_id bigint references public.exams(id) on delete cascade,
  title text not null,
  description text,
  event_date timestamp with time zone not null,
  status text check (status in ('Upcoming', 'Ongoing', 'Past')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.exams enable row level security;
alter table public.timeline_events enable row level security;

-- Policies (Public Read)
create policy "Allow public read access exams" on public.exams for select using (true);
create policy "Allow public read access events" on public.timeline_events for select using (true);

-- Insert Dummy Data (JEE Main)
with new_exam as (
  insert into public.exams (title, description, category, exam_format, website_url)
  values (
    'JEE Main 2025 Session 1', 
    'The Joint Entrance Examination (JEE) Main is a national-level entrance exam conducted by the NTA for admission to B.E./B.Tech courses.', 
    'Engineering',
    'Computer Based Test (CBT). PCM. MCQs.',
    'https://jeemain.nta.ac.in/'
  )
  returning id
)
insert into public.timeline_events (exam_id, title, description, event_date, status)
values 
  ((select id from new_exam), 'Registration Starts', 'Online application form available', '2024-11-01 10:00:00+00', 'Past'),
  ((select id from new_exam), 'Exam Date', 'Paper 1 (B.E./B.Tech)', '2025-01-24 09:00:00+00', 'Upcoming');
