// services/database/csv-seed.ts - Complete seed from CSV data files
// This script contains all the data from the CSV files for seeding

import { db } from "./db-config";
import * as schema from "./schema";
import { sql } from "drizzle-orm";

// ========== RIASEC CAREERS DATA (132 careers) ==========
const RIASEC_CAREERS = [
  {
    Title: "Accountants and Auditors",
    Realistic: 1.14,
    Investigative: 3.57,
    Artistic: 1.09,
    Social: 2.13,
    Enterprising: 3.86,
    Conventional: 7,
    desc: "Analyze financial records to ensure accuracy and compliance with regulations.",
  },
  {
    Title: "Actors",
    Realistic: 2.31,
    Investigative: 2.13,
    Artistic: 7,
    Social: 4.1,
    Enterprising: 4,
    Conventional: 1.67,
    desc: "Perform roles in film, theater, or television through acting and character portrayal.",
  },
  {
    Title: "Administrative Law Judges, Adjudicators, and Hearing Officers",
    Realistic: 1.04,
    Investigative: 4.01,
    Artistic: 1.57,
    Social: 3.04,
    Enterprising: 5.24,
    Conventional: 5.39,
    desc: "Preside over hearings and make legal decisions on disputes and administrative matters.",
  },
  {
    Title: "Advanced Tech & Systems Specialists",
    Realistic: 6.52,
    Investigative: 4.94,
    Artistic: 1.37,
    Social: 1.28,
    Enterprising: 1.33,
    Conventional: 4.97,
    desc: "Support development and deployment of advanced technical systems and solutions.",
  },
  {
    Title: "Aerospace Engineers",
    Realistic: 5.37,
    Investigative: 6.14,
    Artistic: 2.45,
    Social: 1.28,
    Enterprising: 2.58,
    Conventional: 4.63,
    desc: "Design, test, and develop aircraft, spacecraft, and related systems.",
  },
  {
    Title: "Agricultural Inspectors",
    Realistic: 5.33,
    Investigative: 4.06,
    Artistic: 1,
    Social: 1.9,
    Enterprising: 3.13,
    Conventional: 5.15,
    desc: "Inspect agricultural products and processes to ensure safety and quality standards.",
  },
  {
    Title: "Agricultural Technology and Operations",
    Realistic: 6.33,
    Investigative: 4.33,
    Artistic: 1.41,
    Social: 1.45,
    Enterprising: 2.01,
    Conventional: 4.41,
    desc: "Oversee agricultural equipment, operations, and technology-based farming processes.",
  },
  {
    Title: "Airfield Operations Specialists",
    Realistic: 4.73,
    Investigative: 3.51,
    Artistic: 1,
    Social: 2.49,
    Enterprising: 4.48,
    Conventional: 5.03,
    desc: "Manage safe airport operations, including coordination of aircraft movement and logistics.",
  },
  {
    Title: "Airline Pilots, Copilots, and Flight Engineers",
    Realistic: 4.74,
    Investigative: 3.17,
    Artistic: 1.43,
    Social: 2.49,
    Enterprising: 3.79,
    Conventional: 4.69,
    desc: "Operate and navigate aircraft while ensuring passenger and flight safety.",
  },
  {
    Title: "Anthropologists and Archeologists",
    Realistic: 4.55,
    Investigative: 6.74,
    Artistic: 3.89,
    Social: 3.32,
    Enterprising: 1.56,
    Conventional: 3.54,
    desc: "Study human cultures, past civilizations, and archaeological artifacts.",
  },
  {
    Title: "Applied and Decorative Arts",
    Realistic: 5.13,
    Investigative: 1.69,
    Artistic: 6.42,
    Social: 2.38,
    Enterprising: 2.93,
    Conventional: 2.62,
    desc: "Create functional or decorative art using various design techniques.",
  },
  {
    Title: "Architects",
    Realistic: 5.21,
    Investigative: 4.18,
    Artistic: 4.55,
    Social: 2.51,
    Enterprising: 3.45,
    Conventional: 4.12,
    desc: "Plan and design buildings and structures with functionality and aesthetics in mind.",
  },
  {
    Title: "Archivists",
    Realistic: 2.78,
    Investigative: 4.58,
    Artistic: 2.95,
    Social: 3.1,
    Enterprising: 1.92,
    Conventional: 6.02,
    desc: "Organize, preserve, and manage historical documents and archival materials.",
  },
  {
    Title: "Astronomers",
    Realistic: 4.85,
    Investigative: 7,
    Artistic: 3.24,
    Social: 2.81,
    Enterprising: 1.99,
    Conventional: 3.97,
    desc: "Study celestial bodies and phenomena to understand the universe.",
  },
  {
    Title: "Athletic Trainers",
    Realistic: 5.54,
    Investigative: 4.39,
    Artistic: 1.09,
    Social: 5.7,
    Enterprising: 2.27,
    Conventional: 3.32,
    desc: "Help individuals improve athletic performance and prevent injuries.",
  },
  {
    Title: "Atmospheric and Space Scientists",
    Realistic: 4.82,
    Investigative: 6.35,
    Artistic: 2.72,
    Social: 2.45,
    Enterprising: 2.69,
    Conventional: 4.48,
    desc: "Research and forecast weather and atmospheric conditions.",
  },
  {
    Title: "Audio and Video Technicians",
    Realistic: 4.4,
    Investigative: 2.23,
    Artistic: 4.65,
    Social: 1.9,
    Enterprising: 2.4,
    Conventional: 4.02,
    desc: "Set up, operate, and maintain audio or visual equipment for recordings and broadcasts.",
  },
  {
    Title: "Automotive Engineers",
    Realistic: 6.48,
    Investigative: 5.7,
    Artistic: 2.44,
    Social: 1.29,
    Enterprising: 2.04,
    Conventional: 4.11,
    desc: "Design and improve vehicle systems, components, and performance.",
  },
  {
    Title: "Aviation Inspectors",
    Realistic: 5.57,
    Investigative: 4.09,
    Artistic: 1,
    Social: 1.43,
    Enterprising: 2.59,
    Conventional: 5.73,
    desc: "Inspect aircraft to ensure compliance with safety standards and regulations.",
  },
  {
    Title: "Bioinformatics Scientists",
    Realistic: 3.74,
    Investigative: 7,
    Artistic: 2.56,
    Social: 1.63,
    Enterprising: 1.27,
    Conventional: 5.03,
    desc: "Apply computational and biological methods to analyze biological data.",
  },
  {
    Title: "Biological Researchers",
    Realistic: 5.25,
    Investigative: 6.92,
    Artistic: 2.31,
    Social: 2.47,
    Enterprising: 2.05,
    Conventional: 4.01,
    desc: "Conduct research on living organisms to understand biological processes.",
  },
  {
    Title: "Biological Technicians",
    Realistic: 5.6,
    Investigative: 5.57,
    Artistic: 1.24,
    Social: 1.98,
    Enterprising: 1.18,
    Conventional: 5.37,
    desc: "Assist scientists by performing lab tests and collecting biological data.",
  },
  {
    Title: "Biologists",
    Realistic: 4.15,
    Investigative: 6.97,
    Artistic: 2.32,
    Social: 2.56,
    Enterprising: 2.93,
    Conventional: 4.5,
    desc: "Study living organisms, their interactions, and life processes.",
  },
  {
    Title: "Biostatisticians",
    Realistic: 2.58,
    Investigative: 7,
    Artistic: 2.65,
    Social: 2.67,
    Enterprising: 1.86,
    Conventional: 4.73,
    desc: "Apply statistical methods to analyze biological and medical data.",
  },
  {
    Title: "Blockchain Engineers",
    Realistic: 3.4,
    Investigative: 5.28,
    Artistic: 2.07,
    Social: 1.57,
    Enterprising: 3.39,
    Conventional: 5.69,
    desc: "Develop and maintain blockchain-based systems and applications.",
  },
  {
    Title: "Budget Analysts",
    Realistic: 1,
    Investigative: 3.81,
    Artistic: 1.53,
    Social: 2.2,
    Enterprising: 4.76,
    Conventional: 6.92,
    desc: "Analyze financial data to help plan and manage organizational budgets.",
  },
  {
    Title: "Business Intelligence Analysts",
    Realistic: 1.12,
    Investigative: 5.46,
    Artistic: 1.95,
    Social: 1.88,
    Enterprising: 4.46,
    Conventional: 5.61,
    desc: "Use data to identify business trends and support strategic decision-making.",
  },
  {
    Title: "CAD Technicians",
    Realistic: 5.65,
    Investigative: 3.89,
    Artistic: 3.86,
    Social: 1.36,
    Enterprising: 1.56,
    Conventional: 5,
    desc: "Create technical drawings and 3D models using computer-aided design software.",
  },
  {
    Title: "Captains, Mates, and Pilots of Water Vessels",
    Realistic: 5.61,
    Investigative: 2.64,
    Artistic: 1,
    Social: 1.88,
    Enterprising: 4.23,
    Conventional: 4.56,
    desc: "Navigate and operate marine vessels safely on waterways.",
  },
  {
    Title: "Career Counselors",
    Realistic: 1,
    Investigative: 3.31,
    Artistic: 3.42,
    Social: 7,
    Enterprising: 4.21,
    Conventional: 3.38,
    desc: "Guide individuals in exploring and planning career paths.",
  },
  {
    Title: "Cartographers and Photogrammetrists",
    Realistic: 4.61,
    Investigative: 5.15,
    Artistic: 3.56,
    Social: 1.77,
    Enterprising: 1.63,
    Conventional: 5.33,
    desc: "Create maps and analyze geographic data using surveying and photogrammetry.",
  },
  {
    Title: "Chefs and Head Cooks",
    Realistic: 5.68,
    Investigative: 1.43,
    Artistic: 2.49,
    Social: 3.02,
    Enterprising: 3.74,
    Conventional: 4.31,
    desc: "Prepare and cook meals while managing kitchen operations.",
  },
  {
    Title: "Chief Executives",
    Realistic: 1.3,
    Investigative: 3.24,
    Artistic: 2.08,
    Social: 3.52,
    Enterprising: 6.88,
    Conventional: 5,
    desc: "Oversee overall operations and strategic direction of an organization.",
  },
  {
    Title: "Choreographers",
    Realistic: 3.67,
    Investigative: 2.08,
    Artistic: 7,
    Social: 4.08,
    Enterprising: 3.8,
    Conventional: 1.88,
    desc: "Create and plan dance routines for performances.",
  },
  {
    Title: "Climate Change Policy Analysts",
    Realistic: 1.37,
    Investigative: 6.73,
    Artistic: 3.11,
    Social: 3.17,
    Enterprising: 4.69,
    Conventional: 4.06,
    desc: "Analyze environmental policies and their impacts on climate change.",
  },
  {
    Title: "Coaches and Scouts",
    Realistic: 4.26,
    Investigative: 2.15,
    Artistic: 2.43,
    Social: 5.31,
    Enterprising: 5.13,
    Conventional: 3.44,
    desc: "Train athletes and develop coaching strategies for performance improvement.",
  },
  {
    Title: "Computer Hardware Engineers",
    Realistic: 5.79,
    Investigative: 5.64,
    Artistic: 1.84,
    Social: 1.79,
    Enterprising: 1.88,
    Conventional: 5.28,
    desc: "Design and develop computer hardware systems and components.",
  },
  {
    Title: "Computer Network Architects",
    Realistic: 4.06,
    Investigative: 5.33,
    Artistic: 2.24,
    Social: 2.19,
    Enterprising: 3.17,
    Conventional: 5.07,
    desc: "Plan and build computer networks for secure communication and data flow.",
  },
  {
    Title: "Computer Programmers",
    Realistic: 3.31,
    Investigative: 5.18,
    Artistic: 2.62,
    Social: 2.01,
    Enterprising: 2.04,
    Conventional: 5.8,
    desc: "Write and test code to build software applications and systems.",
  },
  {
    Title: "Computer Systems Expert",
    Realistic: 3.84,
    Investigative: 6.07,
    Artistic: 1.98,
    Social: 1.97,
    Enterprising: 2.54,
    Conventional: 5.66,
    desc: "Manage and optimize computer systems, including hardware and software integration.",
  },
  {
    Title: "Cost Estimators",
    Realistic: 3.1,
    Investigative: 3.25,
    Artistic: 1.05,
    Social: 1.66,
    Enterprising: 4.71,
    Conventional: 6.44,
    desc: "Estimate project costs by analyzing materials, labor, and production requirements.",
  },
  {
    Title: "Creative and Media Directors",
    Realistic: 2.11,
    Investigative: 2.15,
    Artistic: 6.47,
    Social: 3.33,
    Enterprising: 5.46,
    Conventional: 3.37,
    desc: "Oversee creative vision and production across media, film, or advertising projects.",
  },
  {
    Title: "Creative Arts and Design Professionals",
    Realistic: 3.89,
    Investigative: 2.74,
    Artistic: 7,
    Social: 2.19,
    Enterprising: 2.54,
    Conventional: 2.78,
    desc: "Produce artistic or design-focused work across visual, performing, or applied arts.",
  },
  {
    Title: "Credit Analysts",
    Realistic: 1,
    Investigative: 3.83,
    Artistic: 1,
    Social: 2.42,
    Enterprising: 4.5,
    Conventional: 6.89,
    desc: "Evaluate financial data to determine creditworthiness and lending risk.",
  },
  {
    Title: "Customs and Border Protection Officers",
    Realistic: 3.41,
    Investigative: 2.64,
    Artistic: 1,
    Social: 2.62,
    Enterprising: 4.32,
    Conventional: 5.27,
    desc: "Enforce laws, secure borders, and facilitate legal movement of people and goods.",
  },
  {
    Title: "Customs Brokers",
    Realistic: 2.43,
    Investigative: 1.53,
    Artistic: 1,
    Social: 2.2,
    Enterprising: 5.07,
    Conventional: 6.13,
    desc: "Assist clients with customs regulations, import/export rules, and documentation.",
  },
  {
    Title: "Data and Research Analysts",
    Realistic: 2.51,
    Investigative: 6.34,
    Artistic: 2.29,
    Social: 2.29,
    Enterprising: 2.73,
    Conventional: 5.45,
    desc: "Analyze datasets to extract insights and support research-based decisions.",
  },
  {
    Title: "Data Scientists",
    Realistic: 2.16,
    Investigative: 6.99,
    Artistic: 2.59,
    Social: 1.66,
    Enterprising: 1.71,
    Conventional: 5.4,
    desc: "Use statistical and computational methods to build predictive models and insights.",
  },
  {
    Title: "Database Architects",
    Realistic: 2.69,
    Investigative: 5.68,
    Artistic: 2.22,
    Social: 1.93,
    Enterprising: 2.75,
    Conventional: 5.99,
    desc: "Design, build, and optimize large-scale database systems and architectures.",
  },
  {
    Title: "Digital Designers",
    Realistic: 2.62,
    Investigative: 4.48,
    Artistic: 5.45,
    Social: 2.28,
    Enterprising: 3.58,
    Conventional: 4.13,
    desc: "Create digital layouts, graphics, and interface designs for online platforms.",
  },
  {
    Title: "Early Childhood and Special Education",
    Realistic: 2.59,
    Investigative: 3.3,
    Artistic: 3.9,
    Social: 7,
    Enterprising: 2.21,
    Conventional: 3.49,
    desc: "Teach young children and support learners with special educational needs.",
  },
  {
    Title: "Economists",
    Realistic: 1.54,
    Investigative: 7,
    Artistic: 2.49,
    Social: 2.22,
    Enterprising: 3.8,
    Conventional: 4.34,
    desc: "Study and analyze economic systems, trends, and market behaviors.",
  },
  {
    Title: "Editors",
    Realistic: 1,
    Investigative: 3.11,
    Artistic: 5.16,
    Social: 2.51,
    Enterprising: 4.03,
    Conventional: 4.85,
    desc: "Review, revise, and refine written content for clarity and accuracy.",
  },
  {
    Title: "Energy & Industrial Technicians",
    Realistic: 6.63,
    Investigative: 3.74,
    Artistic: 1.18,
    Social: 1.46,
    Enterprising: 1.5,
    Conventional: 4.75,
    desc: "Operate and maintain industrial or energy-related machinery and systems.",
  },
  {
    Title: "Environmental Compliance Inspectors",
    Realistic: 4.57,
    Investigative: 4.77,
    Artistic: 1.05,
    Social: 2.35,
    Enterprising: 3.21,
    Conventional: 5.84,
    desc: "Monitor compliance with environmental laws and investigate violations.",
  },
  {
    Title: "Farm and Health Managers",
    Realistic: 4.55,
    Investigative: 3.78,
    Artistic: 1.3,
    Social: 2.45,
    Enterprising: 5.23,
    Conventional: 4.72,
    desc: "Manage agricultural or health-related operations to ensure efficient performance.",
  },
  {
    Title: "Financial Consultant",
    Realistic: 1.18,
    Investigative: 3.38,
    Artistic: 1.44,
    Social: 3.05,
    Enterprising: 5.77,
    Conventional: 5.53,
    desc: "Provide financial planning, investment advice, and economic guidance.",
  },
  {
    Title: "Fraud Examiners, Investigators and Analysts",
    Realistic: 1.85,
    Investigative: 4.54,
    Artistic: 1.11,
    Social: 1.84,
    Enterprising: 4.63,
    Conventional: 6.09,
    desc: "Investigate financial irregularities and detect fraud or misconduct.",
  },
  {
    Title: "Geneticists",
    Realistic: 3.95,
    Investigative: 7,
    Artistic: 3.04,
    Social: 2.96,
    Enterprising: 1.69,
    Conventional: 4.41,
    desc: "Study genes, heredity, and genetic variation in living organisms.",
  },
  {
    Title: "Geographers",
    Realistic: 5.19,
    Investigative: 6.73,
    Artistic: 3.7,
    Social: 2.69,
    Enterprising: 2.15,
    Conventional: 3.71,
    desc: "Study Earth's landscapes, human-environment interactions, and spatial patterns.",
  },
  {
    Title: "Geoscientists",
    Realistic: 5.66,
    Investigative: 7,
    Artistic: 2.7,
    Social: 2.23,
    Enterprising: 1.67,
    Conventional: 4.16,
    desc: "Analyze Earth's physical structure, minerals, and geological processes.",
  },
  {
    Title: "Health Education Specialists",
    Realistic: 1.64,
    Investigative: 5.3,
    Artistic: 2.53,
    Social: 6.16,
    Enterprising: 3.2,
    Conventional: 3.98,
    desc: "Promote health awareness and educate communities on wellness practices.",
  },
  {
    Title: "Histology Technicians",
    Realistic: 6.45,
    Investigative: 5.4,
    Artistic: 1.27,
    Social: 2.13,
    Enterprising: 1,
    Conventional: 5.12,
    desc: "Prepare and examine tissue samples for medical diagnosis.",
  },
  {
    Title: "Historians",
    Realistic: 2.42,
    Investigative: 5.19,
    Artistic: 3.61,
    Social: 3.21,
    Enterprising: 2.4,
    Conventional: 4.97,
    desc: "Research and interpret past events using historical sources.",
  },
  {
    Title: "HR Generalist",
    Realistic: 1.22,
    Investigative: 2.18,
    Artistic: 1.38,
    Social: 3.63,
    Enterprising: 5.54,
    Conventional: 5.9,
    desc: "Manage hiring, employee relations, training, and HR processes.",
  },
  {
    Title: "Hydrologic Technicians",
    Realistic: 5.55,
    Investigative: 4.96,
    Artistic: 1,
    Social: 1.53,
    Enterprising: 1.41,
    Conventional: 5.33,
    desc: "Measure and evaluate water resources, flow, and environmental conditions.",
  },
  {
    Title: "Intelligence Analysts",
    Realistic: 2.35,
    Investigative: 5.88,
    Artistic: 2.18,
    Social: 1.91,
    Enterprising: 3.63,
    Conventional: 5.51,
    desc: "Gather intelligence, analyze threats, and support security decision-making.",
  },
  {
    Title: "Interpreters and Translators",
    Realistic: 1.89,
    Investigative: 3.16,
    Artistic: 4.4,
    Social: 3.51,
    Enterprising: 1.88,
    Conventional: 4.64,
    desc: "Convert spoken or written language between two or more languages.",
  },
  {
    Title: "Judges, Magistrate Judges, and Magistrates",
    Realistic: 2.37,
    Investigative: 3.75,
    Artistic: 2.21,
    Social: 4,
    Enterprising: 5.25,
    Conventional: 4.11,
    desc: "Interpret and apply laws to make legal rulings and oversee court proceedings.",
  },
  {
    Title: "K-12 School Teachers",
    Realistic: 2.66,
    Investigative: 3.27,
    Artistic: 3.92,
    Social: 7,
    Enterprising: 2.58,
    Conventional: 3.62,
    desc: "Teach academic subjects and manage classrooms for school-age children.",
  },
  {
    Title: "Landscape Architects",
    Realistic: 5.42,
    Investigative: 4.69,
    Artistic: 4.57,
    Social: 2.63,
    Enterprising: 3.66,
    Conventional: 3.71,
    desc: "Design outdoor spaces and landscapes that balance function and aesthetics.",
  },
  {
    Title: "Lawyers",
    Realistic: 1.17,
    Investigative: 4.52,
    Artistic: 2.32,
    Social: 3.45,
    Enterprising: 5.54,
    Conventional: 4.54,
    desc: "Represent clients in legal matters and provide legal advice.",
  },
  {
    Title: "Legal Secretaries and Administrative Assistants",
    Realistic: 1.52,
    Investigative: 3.16,
    Artistic: 1.59,
    Social: 3.01,
    Enterprising: 4.28,
    Conventional: 6.61,
    desc: "Perform administrative tasks supporting legal processes and documentation.",
  },
  {
    Title: "Legislators",
    Realistic: 1.54,
    Investigative: 3.35,
    Artistic: 2.7,
    Social: 3.69,
    Enterprising: 5.52,
    Conventional: 3.62,
    desc: "Create laws, draft policies, and represent public interests in government.",
  },
  {
    Title: "Logisticians",
    Realistic: 3.2,
    Investigative: 4.42,
    Artistic: 1.04,
    Social: 1.7,
    Enterprising: 4.37,
    Conventional: 6.05,
    desc: "Manage the movement of goods, logistics planning, and supply chain efficiency.",
  },
  {
    Title: "Manufacturing Engineers",
    Realistic: 5.18,
    Investigative: 4.67,
    Artistic: 2.1,
    Social: 1.51,
    Enterprising: 3.06,
    Conventional: 4.48,
    desc: "Develop manufacturing processes, machinery, and system improvements.",
  },
  {
    Title: "Marine Engineers and Naval Architects",
    Realistic: 5.72,
    Investigative: 5.48,
    Artistic: 2.34,
    Social: 1.43,
    Enterprising: 3.43,
    Conventional: 4.44,
    desc: "Design, build, and maintain ships, marine structures, and ocean systems.",
  },
  {
    Title: "Market Research Analysts and Marketing Specialists",
    Realistic: 1.07,
    Investigative: 4.6,
    Artistic: 2.56,
    Social: 2.48,
    Enterprising: 5.52,
    Conventional: 4.62,
    desc: "Analyze market data to understand consumer behavior and inform marketing strategy.",
  },
  {
    Title: "Materials Engineers",
    Realistic: 5.89,
    Investigative: 5.83,
    Artistic: 2.54,
    Social: 1.37,
    Enterprising: 2.06,
    Conventional: 4.11,
    desc: "Develop and test materials for improved performance and industrial use.",
  },
  {
    Title: "Mathematicians",
    Realistic: 3,
    Investigative: 7,
    Artistic: 3.23,
    Social: 1.97,
    Enterprising: 1.16,
    Conventional: 5.27,
    desc: "Study mathematical theories and solve complex quantitative problems.",
  },
  {
    Title: "Mechatronics Engineers",
    Realistic: 5.86,
    Investigative: 5.67,
    Artistic: 2.42,
    Social: 1.46,
    Enterprising: 1.6,
    Conventional: 4.92,
    desc: "Design and integrate mechanical, electronic, and computer systems into automated solutions.",
  },
  {
    Title: "Media Programming Directors",
    Realistic: 1.28,
    Investigative: 2.22,
    Artistic: 3.92,
    Social: 3.71,
    Enterprising: 6.75,
    Conventional: 4.74,
    desc: "Oversee scheduling, content, and strategy for radio, TV, or digital media programming.",
  },
  {
    Title: "Medical Counselors",
    Realistic: 1.35,
    Investigative: 5.27,
    Artistic: 2.81,
    Social: 6.26,
    Enterprising: 2.77,
    Conventional: 3.63,
    desc: "Provide guidance and emotional support to clients facing medical or health challenges.",
  },
  {
    Title: "Medical Scientists",
    Realistic: 4.43,
    Investigative: 7,
    Artistic: 2.3,
    Social: 3.24,
    Enterprising: 2.23,
    Conventional: 3.95,
    desc: "Conduct research to advance medical knowledge and improve human health.",
  },
  {
    Title: "Meeting, Convention, and Event Planners",
    Realistic: 1,
    Investigative: 1.43,
    Artistic: 2.44,
    Social: 4.52,
    Enterprising: 7,
    Conventional: 5.27,
    desc: "Plan and coordinate conferences, events, and large-scale meetings.",
  },
  {
    Title: "Motion Picture Projectionists",
    Realistic: 5.42,
    Investigative: 1.95,
    Artistic: 2.98,
    Social: 2.02,
    Enterprising: 2.08,
    Conventional: 4.58,
    desc: "Operate film projection equipment and manage theater screening systems.",
  },
  {
    Title: "Musicians and Singers",
    Realistic: 2.87,
    Investigative: 1.53,
    Artistic: 6.66,
    Social: 3.4,
    Enterprising: 3.41,
    Conventional: 2.17,
    desc: "Perform or create music for live audiences, recordings, or productions.",
  },
  {
    Title: "Nanosystems Engineers",
    Realistic: 5.38,
    Investigative: 6.09,
    Artistic: 2.43,
    Social: 1.36,
    Enterprising: 2.52,
    Conventional: 4.08,
    desc: "Design nanoscale systems and materials with specialized engineering techniques.",
  },
  {
    Title: "Neuroscience Specialists",
    Realistic: 3.15,
    Investigative: 7,
    Artistic: 2.58,
    Social: 5.44,
    Enterprising: 2.11,
    Conventional: 3.44,
    desc: "Study the brain and nervous system to understand behavior and neurological functions.",
  },
  {
    Title: "News Analysts, Reporters, and Journalists",
    Realistic: 1.47,
    Investigative: 4.16,
    Artistic: 5.09,
    Social: 2.8,
    Enterprising: 3.96,
    Conventional: 3.63,
    desc: "Report news, analyze current events, and communicate information to the public.",
  },
  {
    Title: "Nuclear Technicians",
    Realistic: 5.75,
    Investigative: 4.57,
    Artistic: 1,
    Social: 1.83,
    Enterprising: 2.26,
    Conventional: 5.07,
    desc: "Operate equipment in nuclear facilities and monitor radiation and safety procedures.",
  },
  {
    Title: "Office Administrator",
    Realistic: 2.28,
    Investigative: 1.66,
    Artistic: 1.13,
    Social: 2.72,
    Enterprising: 3.72,
    Conventional: 6.57,
    desc: "Manage administrative tasks, scheduling, and office communication workflows.",
  },
  {
    Title: "Office and General Managers",
    Realistic: 2.42,
    Investigative: 3.2,
    Artistic: 1.44,
    Social: 3.22,
    Enterprising: 5.94,
    Conventional: 5.61,
    desc: "Oversee daily operations and coordinate activities across organizational departments.",
  },
  {
    Title: "Pharmacy Technicians / Aides",
    Realistic: 3.84,
    Investigative: 2.32,
    Artistic: 1,
    Social: 3.25,
    Enterprising: 3.21,
    Conventional: 6.91,
    desc: "Assist pharmacists by preparing medications and managing pharmacy inventory.",
  },
  {
    Title: "Photographers",
    Realistic: 5.49,
    Investigative: 2.29,
    Artistic: 5.18,
    Social: 1.85,
    Enterprising: 2.3,
    Conventional: 3.43,
    desc: "Capture images using cameras and creative visual techniques.",
  },
  {
    Title: "Photonics Engineers",
    Realistic: 5.82,
    Investigative: 5.91,
    Artistic: 2.73,
    Social: 1.4,
    Enterprising: 1.72,
    Conventional: 4.12,
    desc: "Develop devices and systems that manipulate and control light.",
  },
  {
    Title: "Physicists",
    Realistic: 4.95,
    Investigative: 7,
    Artistic: 2.76,
    Social: 2.11,
    Enterprising: 1.82,
    Conventional: 4.86,
    desc: "Study matter, energy, and natural laws through scientific research.",
  },
  {
    Title: "Police and Sheriff's Patrol Officers",
    Realistic: 5.37,
    Investigative: 2.75,
    Artistic: 1.07,
    Social: 3.43,
    Enterprising: 4.09,
    Conventional: 4.35,
    desc: "Enforce laws, conduct patrols, and ensure public safety within communities.",
  },
  {
    Title: "Political Scientists",
    Realistic: 1,
    Investigative: 6.62,
    Artistic: 3.78,
    Social: 3.47,
    Enterprising: 3.7,
    Conventional: 3.6,
    desc: "Research political systems, policies, and government behavior.",
  },
  {
    Title: "Project and Technical Managers",
    Realistic: 2.95,
    Investigative: 3.73,
    Artistic: 1.75,
    Social: 2.49,
    Enterprising: 5.36,
    Conventional: 5.4,
    desc: "Lead project teams and oversee technical development, timelines, and resources.",
  },
  {
    Title: "Property and Hospitality Managers",
    Realistic: 3.14,
    Investigative: 2.2,
    Artistic: 1.55,
    Social: 3.37,
    Enterprising: 6.27,
    Conventional: 5.17,
    desc: "Manage property operations or hospitality services for guests and tenants.",
  },
  {
    Title: "Public Relations Specialists",
    Realistic: 1,
    Investigative: 2.79,
    Artistic: 4.72,
    Social: 3.94,
    Enterprising: 5.81,
    Conventional: 3.47,
    desc: "Shape public image and manage communication between organizations and the public.",
  },
  {
    Title: "Radiologic Technologists and Technicians",
    Realistic: 6.25,
    Investigative: 4.63,
    Artistic: 1,
    Social: 3.58,
    Enterprising: 1,
    Conventional: 4.87,
    desc: "Perform imaging procedures to assist in diagnosing medical conditions.",
  },
  {
    Title: "Records Manager",
    Realistic: 1.89,
    Investigative: 2.29,
    Artistic: 1.55,
    Social: 3.48,
    Enterprising: 3.83,
    Conventional: 6.54,
    desc: "Organize and maintain information, files, and organizational records.",
  },
  {
    Title: "Recreational Therapists",
    Realistic: 3.88,
    Investigative: 4.03,
    Artistic: 3.12,
    Social: 6.69,
    Enterprising: 2.32,
    Conventional: 2.67,
    desc: "Help individuals improve well-being through structured recreational activities.",
  },
  {
    Title: "Regulatory Affairs Specialists",
    Realistic: 1.48,
    Investigative: 3.33,
    Artistic: 1,
    Social: 2.46,
    Enterprising: 4.46,
    Conventional: 6.32,
    desc: "Ensure products and practices comply with regulatory standards and policies.",
  },
  {
    Title: "Sales and Marketing Managers",
    Realistic: 1.44,
    Investigative: 2.39,
    Artistic: 2.76,
    Social: 3.91,
    Enterprising: 6.48,
    Conventional: 4.41,
    desc: "Oversee sales operations and marketing strategies to drive business growth.",
  },
  {
    Title: "Sales Engineers",
    Realistic: 3.16,
    Investigative: 3.66,
    Artistic: 1.79,
    Social: 2.87,
    Enterprising: 5.81,
    Conventional: 4.49,
    desc: "Explain and support the sale of technical or engineering-related products.",
  },
  {
    Title: "School Psychologists",
    Realistic: 1,
    Investigative: 5,
    Artistic: 3.31,
    Social: 6.77,
    Enterprising: 2.82,
    Conventional: 4.01,
    desc: "Provide psychological assessment and support for students in educational settings.",
  },
  {
    Title: "Search Marketing Strategists",
    Realistic: 1,
    Investigative: 3.81,
    Artistic: 3.23,
    Social: 2.7,
    Enterprising: 5.53,
    Conventional: 4.69,
    desc: "Optimize online visibility and advertising through search-engine strategies.",
  },
  {
    Title: "Skincare Specialists",
    Realistic: 5.8,
    Investigative: 2.06,
    Artistic: 2.92,
    Social: 4.06,
    Enterprising: 3.01,
    Conventional: 3.15,
    desc: "Provide skincare treatments and cosmetic procedures to clients.",
  },
  {
    Title: "Sociologists",
    Realistic: 1.61,
    Investigative: 6.43,
    Artistic: 3.96,
    Social: 4.42,
    Enterprising: 3.08,
    Conventional: 3.57,
    desc: "Study social behavior, interactions, and societal structures.",
  },
  {
    Title: "Software Developers",
    Realistic: 3.93,
    Investigative: 5.86,
    Artistic: 2.26,
    Social: 1.88,
    Enterprising: 1.87,
    Conventional: 5.46,
    desc: "Design, develop, and maintain software applications and systems.",
  },
  {
    Title: "Sound Engineering Technicians",
    Realistic: 5.04,
    Investigative: 2.6,
    Artistic: 4.44,
    Social: 1.79,
    Enterprising: 1.92,
    Conventional: 4.26,
    desc: "Operate sound equipment for recording, mixing, and live audio production.",
  },
  {
    Title: "Space & Product Designers",
    Realistic: 4.21,
    Investigative: 3.36,
    Artistic: 6.07,
    Social: 2.57,
    Enterprising: 3.65,
    Conventional: 3.5,
    desc: "Design physical products or spatial concepts with creative and functional focus.",
  },
  {
    Title: "Statisticians",
    Realistic: 2.51,
    Investigative: 4.5,
    Artistic: 1.25,
    Social: 1.43,
    Enterprising: 1.78,
    Conventional: 6.64,
    desc: "Analyze data using mathematical models and statistical methods.",
  },
  {
    Title: "Sustainability Specialists",
    Realistic: 2.06,
    Investigative: 5.2,
    Artistic: 2.5,
    Social: 2.95,
    Enterprising: 5.09,
    Conventional: 4.41,
    desc: "Promote sustainable practices and environmental stewardship in organizations.",
  },
  {
    Title: "Teaching and Classroom Support Staff",
    Realistic: 2.49,
    Investigative: 2.8,
    Artistic: 2.54,
    Social: 6.72,
    Enterprising: 2.56,
    Conventional: 4.31,
    desc: "Assist teachers in classroom activities and student support tasks.",
  },
  {
    Title: "Training and Development Specialists",
    Realistic: 1.97,
    Investigative: 3.92,
    Artistic: 3.09,
    Social: 5.66,
    Enterprising: 3.76,
    Conventional: 3.93,
    desc: "Develop training programs and support employee learning and development.",
  },
  {
    Title: "Transit and Railroad Police",
    Realistic: 5.87,
    Investigative: 2.42,
    Artistic: 1,
    Social: 2.55,
    Enterprising: 3.28,
    Conventional: 5.06,
    desc: "Enforce security and safety regulations within transportation systems.",
  },
  {
    Title: "Treasurers and Controllers",
    Realistic: 1,
    Investigative: 2.4,
    Artistic: 1.28,
    Social: 2.7,
    Enterprising: 6.22,
    Conventional: 6.15,
    desc: "Manage financial assets, budgets, and organizational accounting responsibilities.",
  },
  {
    Title: "Umpires, Referees, and Other Sports Officials",
    Realistic: 4.38,
    Investigative: 1.65,
    Artistic: 1.09,
    Social: 3.34,
    Enterprising: 5.69,
    Conventional: 4.64,
    desc: "Officiate sporting events and enforce game rules.",
  },
  {
    Title: "University & College Instructors (Arts & Humanities)",
    Realistic: 2.81,
    Investigative: 5.06,
    Artistic: 3.95,
    Social: 6.85,
    Enterprising: 2.57,
    Conventional: 3.4,
    desc: "Teach and conduct research in arts and humanities disciplines at the university level.",
  },
  {
    Title: "University & College Instructors (Social Sciences & Professional)",
    Realistic: 2.57,
    Investigative: 5.19,
    Artistic: 3.4,
    Social: 6.78,
    Enterprising: 2.88,
    Conventional: 3.54,
    desc: "Teach and research in social sciences or professional studies at the university level.",
  },
  {
    Title: "University & College Instructors (STEM & Technical)",
    Realistic: 3.8,
    Investigative: 5.68,
    Artistic: 3.25,
    Social: 6.18,
    Enterprising: 2.26,
    Conventional: 3.72,
    desc: "Teach and research STEM or technical subjects at the university level.",
  },
  {
    Title: "Veterinary Technologists and Technicians",
    Realistic: 6.71,
    Investigative: 5.26,
    Artistic: 1,
    Social: 3.02,
    Enterprising: 1,
    Conventional: 4.56,
    desc: "Assist veterinarians by caring for animals and performing clinical tasks.",
  },
  {
    Title: "Visual and Appearance Designers",
    Realistic: 4.22,
    Investigative: 2.24,
    Artistic: 6.13,
    Social: 2.37,
    Enterprising: 3.79,
    Conventional: 3.54,
    desc: "Improve personal appearance through styling, grooming, and aesthetic design.",
  },
  {
    Title: "Vocational and Enrichment Teachers",
    Realistic: 2.86,
    Investigative: 3.29,
    Artistic: 3.8,
    Social: 6.93,
    Enterprising: 2.76,
    Conventional: 3.22,
    desc: "Teach practical skills or enrichment subjects in non-traditional education settings.",
  },
  {
    Title: "Web Administrators",
    Realistic: 2.57,
    Investigative: 4.42,
    Artistic: 2.28,
    Social: 2.23,
    Enterprising: 3.74,
    Conventional: 5.74,
    desc: "Manage and maintain websites, servers, and related online infrastructure.",
  },
  {
    Title: "Web Developers",
    Realistic: 2.95,
    Investigative: 5.06,
    Artistic: 3.07,
    Social: 2.24,
    Enterprising: 2.89,
    Conventional: 5.09,
    desc: "Build and maintain websites, applications, and interactive online tools.",
  },
  {
    Title: "Wind Energy Engineers",
    Realistic: 5.9,
    Investigative: 4.54,
    Artistic: 2.22,
    Social: 1.43,
    Enterprising: 3.12,
    Conventional: 4.12,
    desc: "Design and optimize systems that generate energy from wind resources.",
  },
  {
    Title: "Writers and Authors",
    Realistic: 1.99,
    Investigative: 2.95,
    Artistic: 4.79,
    Social: 2.63,
    Enterprising: 3.72,
    Conventional: 4.33,
    desc: "Create written content such as books, articles, or scripts.",
  },
];

// ========== ROADMAP TEMPLATES DATA (7 templates) ==========
const ROADMAP_TEMPLATES = [
  {
    id: 1,
    title: "Arts & Humanities Roadmap",
    semester: JSON.stringify({
      year1: [
        "Writing skills",
        "Communication",
        "Critical thinking",
        "Basic research",
      ],
      year2: [
        "Field research",
        "Presentation skills",
        "Social awareness",
        "Data interpretation",
      ],
      year3: [
        "Project writing",
        "Survey analysis",
        "Public speaking",
        "Digital literacy",
      ],
    }),
    internships: JSON.stringify([
      "NGOs",
      "Community centers",
      "Media houses",
      "Government welfare departments",
    ]),
    exams: JSON.stringify([
      "SSC CGL",
      "SSC CHSL",
      "State PSC",
      "UPSC (Humanities-friendly)",
      "Teaching exams (after B.Ed)",
    ]),
    certifications: JSON.stringify([
      "Content writing",
      "Digital marketing",
      "Research methodology",
      "MS Office / Google Workspace",
    ]),
    upscaling: JSON.stringify([
      "MA",
      "MSW",
      "MBA",
      "M.Ed",
      "Journalism & Mass Communication",
    ]),
  },
  {
    id: 2,
    title: "Science & Research Roadmap",
    semester: JSON.stringify({
      year1: ["Lab safety", "Basic experiments", "Mathematical foundation"],
      year2: ["Data analysis", "Scientific writing", "Research methods"],
      year3: ["Advanced labs", "Statistical tools", "Research project"],
    }),
    internships: JSON.stringify([
      "Research labs",
      "Agriculture departments",
      "Environmental agencies",
      "Hospitals (for biosciences)",
    ]),
    exams: JSON.stringify([
      "ISRO technician exams",
      "DRDO technician",
      "FCI",
      "ESIC",
      "SSC Scientific Assistant",
    ]),
    certifications: JSON.stringify([
      "SPSS / Statistical tools",
      "Lab Technician Basics",
      "Environmental studies",
      "Python for Data Analysis",
    ]),
    upscaling: JSON.stringify([
      "MSc",
      "Integrated PhD",
      "Medical Lab Technology",
      "MBA",
    ]),
  },
  {
    id: 3,
    title: "Commerce & Business Roadmap",
    semester: JSON.stringify({
      year1: ["Accounting basics", "Spreadsheets", "Communication"],
      year2: ["Finance fundamentals", "Marketing basics", "Business analytics"],
      year3: [
        "Taxation",
        "Auditing",
        "Entrepreneurship",
        "Presentation skills",
      ],
    }),
    internships: JSON.stringify([
      "CA firms",
      "Local businesses",
      "Banks",
      "Accounting and taxation offices",
    ]),
    exams: JSON.stringify([
      "IBPS PO/Clerk",
      "RBI Assistant",
      "SSC CGL",
      "Insurance (LIC/GIC)",
      "State PSC",
    ]),
    certifications: JSON.stringify([
      "Tally",
      "GST filing",
      "Financial modeling",
      "Advanced Excel",
      "Digital marketing",
    ]),
    upscaling: JSON.stringify(["MBA", "M.Com", "CA", "CMA", "CS"]),
  },
  {
    id: 4,
    title: "Computer & IT Roadmap",
    semester: JSON.stringify({
      year1: [
        "Programming basics (Python/Java)",
        "Databases",
        "Logical reasoning",
      ],
      year2: ["Web development", "DSA", "Cloud basics", "API usage"],
      year3: ["ML foundations", "Software projects", "Internships"],
    }),
    internships: JSON.stringify([
      "Local IT firms",
      "Freelance software development",
      "Government IT departments",
      "Digital service centers",
    ]),
    exams: JSON.stringify([
      "NIC Technical Assistant",
      "ISRO/DRDO technical roles",
      "Bank IT Officer",
      "SSC Scientific Assistant",
    ]),
    certifications: JSON.stringify([
      "Python / Java",
      "SQL",
      "Cloud (AWS/Azure basics)",
      "Cybersecurity essentials",
    ]),
    upscaling: JSON.stringify(["MCA", "MSc CS", "MBA IT", "AI/ML PG Diploma"]),
  },
  {
    id: 5,
    title: "Professional & Vocational Roadmap",
    semester: JSON.stringify({
      year1: [
        "Field exposure",
        "Communication skills",
        "Foundational subject skills",
      ],
      year2: [
        "Practical training",
        "Lesson planning",
        "Domain-specific techniques",
      ],
      year3: ["Licensing exam preparation", "Advanced field internship"],
    }),
    internships: JSON.stringify([
      "Schools",
      "Hospitals",
      "NGOs",
      "Tourism boards",
    ]),
    exams: JSON.stringify([
      "Teacher Eligibility Test",
      "Nursing recruitment exams",
      "Social welfare jobs",
      "Tourism development boards",
    ]),
    certifications: JSON.stringify([
      "First Aid",
      "Child psychology",
      "Hospitality basics",
      "Safety training",
    ]),
    upscaling: JSON.stringify(["M.Ed", "MSc Nursing", "MSW", "MBA HR/Tourism"]),
  },
  {
    id: 6,
    title: "Entrepreneurship & Skill-Aligned Roadmap",
    semester: JSON.stringify({
      year1: ["Communication", "Digital tools", "Finance basics"],
      year2: ["Marketing", "Customer research", "Prototyping"],
      year3: ["Business planning", "Pitching", "Joining incubators"],
    }),
    internships: JSON.stringify([
      "Local startups",
      "E-commerce sellers",
      "Government entrepreneurship centers",
    ]),
    exams: JSON.stringify([]),
    certifications: JSON.stringify([
      "Digital marketing",
      "Startup fundamentals",
      "Accounting basics",
      "Design tools (Canva/Figma)",
    ]),
    upscaling: JSON.stringify(["MBA", "Entrepreneurship diplomas"]),
  },
  {
    id: 7,
    title: "Fallback template for uncommon or generic degrees",
    semester: JSON.stringify({
      year1: ["Soft skills", "Digital literacy"],
      year2: ["Industry-relevant skills", "Basic internship"],
      year3: ["Electives", "Final internship"],
    }),
    internships: JSON.stringify([
      "Small businesses",
      "NGOs",
      "Government departments",
    ]),
    exams: JSON.stringify(["SSC", "Banking", "Railways", "State PSC"]),
    certifications: JSON.stringify([
      "MS Office",
      "Intro to computers",
      "Communication skills",
    ]),
    upscaling: JSON.stringify([
      "PG Diploma",
      "Masters (in interest area)",
      "MBA",
    ]),
  },
];

/**
 * Clear and recreate CSV-related tables with raw SQL
 */
export async function clearCsvData() {
  console.log("🗑️ Dropping and recreating CSV tables with correct schema...");

  try {
    // Drop tables if they exist - wrap each in try-catch to handle gracefully
    try {
      await db.run(sql`DROP TABLE IF EXISTS course_college`);
    } catch (e) {
      console.log("course_college not found, skipping...");
    }
    try {
      await db.run(sql`DROP TABLE IF EXISTS career_course`);
    } catch (e) {
      console.log("career_course not found, skipping...");
    }
    try {
      await db.run(sql`DROP TABLE IF EXISTS courses`);
    } catch (e) {
      console.log("courses not found, skipping...");
    }
    try {
      await db.run(sql`DROP TABLE IF EXISTS roadmap_templates`);
    } catch (e) {
      console.log("roadmap_templates not found, skipping...");
    }
    try {
      await db.run(sql`DROP TABLE IF EXISTS careers`);
    } catch (e) {
      console.log("careers not found, skipping...");
    }
    try {
      await db.run(sql`DROP TABLE IF EXISTS college_list`);
    } catch (e) {
      console.log("college_list not found, skipping...");
    }
    console.log("✅ Old tables dropped (or didn't exist)");

    // Recreate careers table with description column
    await db.run(sql`
      CREATE TABLE IF NOT EXISTS careers (
        id INTEGER PRIMARY KEY NOT NULL,
        career_name TEXT NOT NULL UNIQUE,
        r REAL NOT NULL,
        i REAL NOT NULL,
        a REAL NOT NULL,
        s REAL NOT NULL,
        e REAL NOT NULL,
        c REAL NOT NULL,
        description TEXT
      )
    `);

    // Recreate roadmap_templates table
    await db.run(sql`
      CREATE TABLE IF NOT EXISTS roadmap_templates (
        id INTEGER PRIMARY KEY NOT NULL,
        title TEXT NOT NULL UNIQUE,
        semester TEXT,
        internships TEXT,
        exams TEXT,
        certifications TEXT,
        upscaling TEXT
      )
    `);

    // Recreate courses table
    await db.run(sql`
      CREATE TABLE IF NOT EXISTS courses (
        id INTEGER PRIMARY KEY NOT NULL,
        course_name TEXT NOT NULL UNIQUE,
        roadmap_id INTEGER,
        stream TEXT
      )
    `);

    // Recreate career_course table
    await db.run(sql`
      CREATE TABLE IF NOT EXISTS career_course (
        id INTEGER PRIMARY KEY NOT NULL,
        career_name TEXT NOT NULL,
        course_name TEXT NOT NULL
      )
    `);

    // Recreate course_college table
    await db.run(sql`
      CREATE TABLE IF NOT EXISTS course_college (
        id INTEGER PRIMARY KEY NOT NULL,
        course_name TEXT NOT NULL,
        college_name TEXT NOT NULL
      )
    `);

    console.log("✅ Tables recreated with correct schema");
  } catch (error) {
    console.error("❌ Error clearing/recreating CSV tables:", error);
    throw error;
  }
}

/**
 * Seed roadmap templates (7 templates)
 */
export async function seedRoadmapTemplates() {
  console.log("🗺️ Seeding roadmap templates...");

  for (const template of ROADMAP_TEMPLATES) {
    await db
      .insert(schema.roadmapTemplates)
      .values(template)
      .onConflictDoNothing();
  }

  console.log(`✅ Added ${ROADMAP_TEMPLATES.length} roadmap templates`);
}

/**
 * Seed careers with RIASEC scores (132 careers)
 */
export async function seedCareers() {
  console.log("💼 Seeding careers...");

  for (let i = 0; i < RIASEC_CAREERS.length; i++) {
    const career = RIASEC_CAREERS[i];
    await db
      .insert(schema.careers)
      .values({
        id: i + 1,
        careerName: career.Title,
        r: career.Realistic,
        i: career.Investigative,
        a: career.Artistic,
        s: career.Social,
        e: career.Enterprising,
        c: career.Conventional,
        description: career.desc,
      })
      .onConflictDoNothing();
  }

  console.log(`✅ Added ${RIASEC_CAREERS.length} careers`);
}

/**
 * Seed colleges from CSV data (ALL 136 colleges from J&K)
 */
export async function seedColleges() {
  console.log("🏫 Seeding all colleges from CSV...");

  // ALL 136 colleges from CollegeList_rows.csv
  const colleges = [
    {
      name: "Abdul Ahad Azad Memorial College Bemina",
      district: "Srinagar",
      location: "Urban",
      collegeType: "Constituent / University College",
      management: "State Government",
      yearOfEstablishment: 1970,
      universityName: "Cluster University Srinagar",
      forGirls: 0,
    },
    {
      name: "Amar Singh College Srinagar",
      district: "Srinagar",
      location: "Urban",
      collegeType: "Constituent / University College",
      management: "State Government",
      yearOfEstablishment: 1942,
      universityName: "Cluster University Srinagar",
      forGirls: 0,
    },
    {
      name: "Gandhi Memorial College Srinagar",
      district: "Srinagar",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1943,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government College For Women Bhagwati Nagar Jammu",
      district: "Jammu",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 1,
    },
    {
      name: "Government College for Women M A Road Srinagar",
      district: "Srinagar",
      location: "Urban",
      collegeType: "Constituent / University College",
      management: "State Government",
      yearOfEstablishment: 1950,
      universityName: "Cluster University Srinagar",
      forGirls: 1,
    },
    {
      name: "Government College for Women Parade Ground Jammu",
      district: "Jammu",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1944,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 1,
    },
    {
      name: "Government College for Women Udhampur",
      district: "Udhampur",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1986,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 1,
    },
    {
      name: "Government Degree College Ajas",
      district: "Bandipora",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Akhnoor",
      district: "Jammu",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Anantnag",
      district: "Anantnag",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1950,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Awantipora",
      district: "Pulwama",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Bani",
      district: "Kathua",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Banihal",
      district: "Ramban",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Baramulla",
      district: "Baramulla",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1943,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Basohli",
      district: "Kathua",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Batote",
      district: "Ramban",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Bhaderwah",
      district: "Doda",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1955,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Bijbahera",
      district: "Anantnag",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Billawar",
      district: "Kathua",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Bishnah",
      district: "Jammu",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Bomai",
      district: "Baramulla",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Boniyar",
      district: "Baramulla",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2020,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Budhal",
      district: "Rajouri",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Chadoora",
      district: "Budgam",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Charar i Sharief",
      district: "Budgam",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2011,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Chatroo",
      district: "Kishtwar",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Chenani",
      district: "Udhampur",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College D H Pora",
      district: "Kulgam",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2011,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Danghiwacha",
      district: "Baramulla",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Darhal",
      district: "Rajouri",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Dharmari",
      district: "Reasi",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Doda",
      district: "Doda",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1989,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Doongi",
      district: "Rajouri",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Dooru Kashmir",
      district: "Anantnag",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Dudu Basantgarh",
      district: "Udhampur",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College for Women Kathua",
      district: "Kathua",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 1,
    },
    {
      name: "Government Degree College For Women Pulwama Kashmir",
      district: "Pulwama",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 1,
    },
    {
      name: "Government Degree College Frisal Homeshalibugh",
      district: "Kulgam",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "University",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Ganderbal",
      district: "Ganderbal",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2002,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Ghagwal",
      district: "Samba",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Gurez",
      district: "Bandipora",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Hadipora",
      district: "Baramulla",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2011,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Hajin",
      district: "Bandipora",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Handwara",
      district: "Kupwara",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1988,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Hiranagar",
      district: "Kathua",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Jindrah",
      district: "Jammu",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2012,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Jourian",
      district: "Jammu",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Kakryal Katra",
      district: "Reasi",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Kalakote",
      district: "Rajouri",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2012,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Kangan",
      district: "Ganderbal",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2011,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Kastigarh",
      district: "Doda",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Kathua",
      district: "Kathua",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1961,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College KhanSahib Budgam",
      district: "Budgam",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Khour",
      district: "Jammu",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2012,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Kilhotran",
      district: "Doda",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Killam",
      district: "Kulgam",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Kishtwar",
      district: "Kishtwar",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1986,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Kokernag",
      district: "Anantnag",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Kralpora",
      district: "Kupwara",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Kulgam",
      district: "Kulgam",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2004,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Kupwara",
      district: "Kupwara",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1988,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Langate",
      district: "Kupwara",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Magam",
      district: "Budgam",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2011,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Mahanpur",
      district: "Kathua",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2012,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Majalta",
      district: "Udhampur",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2016,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Mandi",
      district: "Poonch",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Marh",
      district: "Jammu",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Marheen",
      district: "Kathua",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Mattan",
      district: "Anantnag",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Mendhar",
      district: "Poonch",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Nagrota",
      district: "Jammu",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Neeli Nallah Udhampur",
      district: "Udhampur",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Nowshera",
      district: "Rajouri",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Paloura",
      district: "Jammu",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Pampore",
      district: "Pulwama",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2011,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Pattan",
      district: "Baramulla",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Peeri Kotranka",
      district: "Rajouri",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Pouni",
      district: "Reasi",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "University",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Pulwama",
      district: "Pulwama",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1986,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Purmandal",
      district: "Samba",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Qazigund",
      district: "Kulgam",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College R S Pura",
      district: "Jammu",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Rajpora",
      district: "Pulwama",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Ramban",
      district: "Ramban",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Ramgarh",
      district: "Samba",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Ramkote",
      district: "Kathua",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Ramnagar",
      district: "Udhampur",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Sainik Colony Kunjwani",
      district: "Jammu",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Sarh Bagga Mahore",
      district: "Reasi",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2012,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Shopian",
      district: "Shopian",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1988,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Sidhra",
      district: "Jammu",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Sogam",
      district: "Kupwara",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Soibugh",
      district: "Budgam",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Sopore",
      district: "Baramulla",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1951,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Sumbal",
      district: "Bandipora",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2010,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Sunderbani",
      district: "Rajouri",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2012,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Surankote",
      district: "Poonch",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2012,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Tangdar Kupwara Kashmir",
      district: "Kupwara",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Tangmarg",
      district: "Baramulla",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "Central Government",
      yearOfEstablishment: 2011,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Thanamandi",
      district: "Rajouri",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Thathri",
      district: "Doda",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2012,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Thindim Kreeri",
      district: "Baramulla",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Tral",
      district: "Pulwama",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1988,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Tulail",
      district: "Bandipora",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Udhampur",
      district: "Udhampur",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1961,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Ukhral",
      district: "Ramban",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Uri",
      district: "Baramulla",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Uttersoo",
      district: "Anantnag",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Vailoo Larnoo",
      district: "Anantnag",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2011,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Verinag",
      district: "Anantnag",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Vijaypur",
      district: "Samba",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Degree College Vilgam",
      district: "Kupwara",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Degree College Zainapora",
      district: "Shopian",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2020,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Gandhi Memorial Science College",
      district: "Jammu",
      location: "Urban",
      collegeType: "Constituent / University College",
      management: "State Government",
      yearOfEstablishment: 1907,
      universityName: "Cluster University of Jammu",
      forGirls: 0,
    },
    {
      name: "Government General Zorawar Singh Memorial Degree College Reasi",
      district: "Reasi",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2003,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government PG College Rajouri",
      district: "Rajouri",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1981,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Government Sheikh ul Alam Memorial Degree College Budgam",
      district: "Budgam",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Government Women College Anantnag",
      district: "Anantnag",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1979,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 1,
    },
    {
      name: "Government Women College Baramulla",
      district: "Baramulla",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1986,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 1,
    },
    {
      name: "Government Women College Kupwara",
      district: "Kupwara",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2011,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 1,
    },
    {
      name: "Government Women College Nawakadal Srinagar",
      district: "Srinagar",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1961,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 1,
    },
    {
      name: "Government Women College Sopore",
      district: "Baramulla",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 1,
    },
    {
      name: "Govt Degree College Padder",
      district: "Kishtwar",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Govt. Degree College Gool",
      district: "Ramban",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2012,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Govt. Degree College Hyderpora",
      district: "Srinagar",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "Cluster University Srinagar",
      forGirls: 0,
    },
    {
      name: "Govternment Degree College Beerwah",
      district: "Budgam",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Hamidi Kashmiri Memorial Government Degree College Eidgah Kashmir",
      district: "Srinagar",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2019,
      universityName: "Cluster University Srinagar",
      forGirls: 0,
    },
    {
      name: "Hassan Khoyihami Memorial Degree College Bandipora",
      district: "Bandipora",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Institute of Advanced Studies in Education Srinagar",
      district: "Srinagar",
      location: "Urban",
      collegeType: "Constituent / University College",
      management: "State Government",
      yearOfEstablishment: 1937,
      universityName: "Cluster University Srinagar",
      forGirls: 0,
    },
    {
      name: "Islamia College of Science & Commerce, Srinagar",
      district: "Srinagar",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1961,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Jammu and Kashmir Institute of Mathematical Sciences",
      district: "Srinagar",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "Central Government",
      yearOfEstablishment: 2013,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 0,
    },
    {
      name: "Pt Premnath Dogra GDC Samba",
      district: "Samba",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2005,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Shri Kishan Chander Government Degree College Poonch",
      district: "Poonch",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 1955,
      universityName: "University of Jammu, Jammu Tawi",
      forGirls: 0,
    },
    {
      name: "Sri Pratap College Srinagar",
      district: "Srinagar",
      location: "Urban",
      collegeType: "Constituent / University College",
      management: "State Government",
      yearOfEstablishment: 1905,
      universityName: "Cluster University Srinagar",
      forGirls: 0,
    },
    {
      name: "Srinagar Women's College Zakura",
      district: "Srinagar",
      location: "Urban",
      collegeType: "Affiliated College",
      management: "State Government",
      yearOfEstablishment: 2008,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 1,
    },
    {
      name: "Vishwa Bharti Women's College Rainawari, Srinagar",
      district: "Jammu",
      location: "Rural",
      collegeType: "Affiliated College",
      management: "Local Body",
      yearOfEstablishment: 1979,
      universityName: "University of Kashmir, Srinagar",
      forGirls: 1,
    },
  ];

  // Create college_list table with more fields
  await db.run(sql`DROP TABLE IF EXISTS college_list`);
  await db.run(sql`
    CREATE TABLE college_list (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      district TEXT,
      location TEXT,
      college_type TEXT,
      management TEXT,
      year_of_establishment INTEGER,
      university_name TEXT,
      for_girls INTEGER DEFAULT 0
    )
  `);

  for (const college of colleges) {
    await db.run(sql`
      INSERT INTO college_list (name, district, location, college_type, management, year_of_establishment, university_name, for_girls)
      VALUES (${college.name}, ${college.district}, ${college.location}, ${college.collegeType}, ${college.management}, ${college.yearOfEstablishment}, ${college.universityName}, ${college.forGirls})
    `);
  }

  console.log(`✅ Added ${colleges.length} colleges`);
}

/**
 * Full seed from CSV data
 */
export async function seedFromCsv() {
  console.log("🌱 Starting CSV data seeding...");

  try {
    await clearCsvData();
    await seedRoadmapTemplates();
    await seedCareers();
    await seedColleges();

    console.log("🎉 CSV seeding completed!");
    console.log("📊 Summary:");
    console.log(`   - ${ROADMAP_TEMPLATES.length} roadmap templates`);
    console.log(`   - ${RIASEC_CAREERS.length} careers with RIASEC scores`);
    console.log(`   - 136 colleges from J&K`);
  } catch (error) {
    console.error("❌ Error seeding from CSV:", error);
    throw error;
  }
}

export default {
  clearCsvData,
  seedRoadmapTemplates,
  seedCareers,
  seedColleges,
  seedFromCsv,
  // Export data for external use
  RIASEC_CAREERS,
  ROADMAP_TEMPLATES,
};
