// services/database/seed-all.ts - SIMPLE seeding using existing data

import { db } from "./db-config";
import { sql } from "drizzle-orm";
// Import ALL existing data from csv-seed.ts
import csvSeed from "./csv-seed";

const { RIASEC_CAREERS } = csvSeed;

// 136 colleges - copied directly from CollegeList_rows.csv
const COLLEGES = [
  {
    name: "Abdul Ahad Azad Memorial College Bemina",
    district: "Srinagar",
    location: "Urban",
    collegeType: "Constituent / University College",
    management: "State Government",
    yearOfEstablishment: 1970,
    universityName: "Cluster University Srinagar",
    forGirls: 0,
  },
  {
    name: "Amar Singh College Srinagar",
    district: "Srinagar",
    location: "Urban",
    collegeType: "Constituent / University College",
    management: "State Government",
    yearOfEstablishment: 1942,
    universityName: "Cluster University Srinagar",
    forGirls: 0,
  },
  {
    name: "Gandhi Memorial College Srinagar",
    district: "Srinagar",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1943,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government College For Women Bhagwati Nagar Jammu",
    district: "Jammu",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 1,
  },
  {
    name: "Government College for Women M A Road Srinagar",
    district: "Srinagar",
    location: "Urban",
    collegeType: "Constituent / University College",
    management: "State Government",
    yearOfEstablishment: 1950,
    universityName: "Cluster University Srinagar",
    forGirls: 1,
  },
  {
    name: "Government College for Women Parade Ground Jammu",
    district: "Jammu",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1944,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 1,
  },
  {
    name: "Government College for Women Udhampur",
    district: "Udhampur",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1986,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 1,
  },
  {
    name: "Government Degree College Ajas",
    district: "Bandipora",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Akhnoor",
    district: "Jammu",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Anantnag",
    district: "Anantnag",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1950,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Awantipora",
    district: "Pulwama",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Bani",
    district: "Kathua",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Banihal",
    district: "Ramban",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Baramulla",
    district: "Baramulla",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1943,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Basohli",
    district: "Kathua",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Batote",
    district: "Ramban",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Bhaderwah",
    district: "Doda",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1955,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Bijbahera",
    district: "Anantnag",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Billawar",
    district: "Kathua",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Bishnah",
    district: "Jammu",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Bomai",
    district: "Baramulla",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Boniyar",
    district: "Baramulla",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2020,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Budhal",
    district: "Rajouri",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Chadoora",
    district: "Budgam",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Charar i Sharief",
    district: "Budgam",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2011,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Chatroo",
    district: "Kishtwar",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Chenani",
    district: "Udhampur",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College D H Pora",
    district: "Kulgam",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2011,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Danghiwacha",
    district: "Baramulla",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Darhal",
    district: "Rajouri",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Dharmari",
    district: "Reasi",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Doda",
    district: "Doda",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1989,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Doongi",
    district: "Rajouri",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Dooru Kashmir",
    district: "Anantnag",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Dudu Basantgarh",
    district: "Udhampur",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College for Women Kathua",
    district: "Kathua",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 1,
  },
  {
    name: "Government Degree College For Women Pulwama Kashmir",
    district: "Pulwama",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 1,
  },
  {
    name: "Government Degree College Frisal Homeshalibugh",
    district: "Kulgam",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "University",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Ganderbal",
    district: "Ganderbal",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2002,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Ghagwal",
    district: "Samba",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Gurez",
    district: "Bandipora",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Hadipora",
    district: "Baramulla",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2011,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Hajin",
    district: "Bandipora",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Handwara",
    district: "Kupwara",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1988,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Hiranagar",
    district: "Kathua",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Jindrah",
    district: "Jammu",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2012,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Jourian",
    district: "Jammu",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Kakryal Katra",
    district: "Reasi",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Kalakote",
    district: "Rajouri",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2012,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Kangan",
    district: "Ganderbal",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2011,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Kastigarh",
    district: "Doda",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Kathua",
    district: "Kathua",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1961,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College KhanSahib Budgam",
    district: "Budgam",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Khour",
    district: "Jammu",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2012,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Kilhotran",
    district: "Doda",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Killam",
    district: "Kulgam",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Kishtwar",
    district: "Kishtwar",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1986,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Kokernag",
    district: "Anantnag",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Kralpora",
    district: "Kupwara",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Kulgam",
    district: "Kulgam",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2004,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Kupwara",
    district: "Kupwara",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1988,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Langate",
    district: "Kupwara",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Magam",
    district: "Budgam",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2011,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Mahanpur",
    district: "Kathua",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2012,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Majalta",
    district: "Udhampur",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2016,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Mandi",
    district: "Poonch",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Marh",
    district: "Jammu",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Marheen",
    district: "Kathua",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Mattan",
    district: "Anantnag",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Mendhar",
    district: "Poonch",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Nagrota",
    district: "Jammu",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Neeli Nallah Udhampur",
    district: "Udhampur",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Nowshera",
    district: "Rajouri",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Paloura",
    district: "Jammu",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Pampore",
    district: "Pulwama",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2011,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Pattan",
    district: "Baramulla",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Peeri Kotranka",
    district: "Rajouri",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Pouni",
    district: "Reasi",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "University",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Pulwama",
    district: "Pulwama",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1986,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Purmandal",
    district: "Samba",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Qazigund",
    district: "Kulgam",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College R S Pura",
    district: "Jammu",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Rajpora",
    district: "Pulwama",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Ramban",
    district: "Ramban",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Ramgarh",
    district: "Samba",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Ramkote",
    district: "Kathua",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Ramnagar",
    district: "Udhampur",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Sainik Colony Kunjwani",
    district: "Jammu",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Sarh Bagga Mahore",
    district: "Reasi",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2012,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Shopian",
    district: "Shopian",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1988,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Sidhra",
    district: "Jammu",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Sogam",
    district: "Kupwara",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Soibugh",
    district: "Budgam",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Sopore",
    district: "Baramulla",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1951,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Sumbal",
    district: "Bandipora",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2010,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Sunderbani",
    district: "Rajouri",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2012,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Surankote",
    district: "Poonch",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2012,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Tangdar Kupwara Kashmir",
    district: "Kupwara",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Tangmarg",
    district: "Baramulla",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "Central Government",
    yearOfEstablishment: 2011,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Thanamandi",
    district: "Rajouri",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Thathri",
    district: "Doda",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2012,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Thindim Kreeri",
    district: "Baramulla",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Tral",
    district: "Pulwama",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1988,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Tulail",
    district: "Bandipora",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Udhampur",
    district: "Udhampur",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1961,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Ukhral",
    district: "Ramban",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Uri",
    district: "Baramulla",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Uttersoo",
    district: "Anantnag",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Vailoo Larnoo",
    district: "Anantnag",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2011,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Verinag",
    district: "Anantnag",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Vijaypur",
    district: "Samba",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Degree College Vilgam",
    district: "Kupwara",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Degree College Zainapora",
    district: "Shopian",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2020,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Gandhi Memorial Science College",
    district: "Jammu",
    location: "Urban",
    collegeType: "Constituent / University College",
    management: "State Government",
    yearOfEstablishment: 1907,
    universityName: "Cluster University of Jammu",
    forGirls: 0,
  },
  {
    name: "Government General Zorawar Singh Memorial Degree College Reasi",
    district: "Reasi",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2003,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government PG College Rajouri",
    district: "Rajouri",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1981,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Government Sheikh ul Alam Memorial Degree College Budgam",
    district: "Budgam",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Government Women College Anantnag",
    district: "Anantnag",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1979,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 1,
  },
  {
    name: "Government Women College Baramulla",
    district: "Baramulla",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1986,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 1,
  },
  {
    name: "Government Women College Kupwara",
    district: "Kupwara",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2011,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 1,
  },
  {
    name: "Government Women College Nawakadal Srinagar",
    district: "Srinagar",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1961,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 1,
  },
  {
    name: "Government Women College Sopore",
    district: "Baramulla",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 1,
  },
  {
    name: "Govt Degree College Padder",
    district: "Kishtwar",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Govt. Degree College Gool",
    district: "Ramban",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2012,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Govt. Degree College Hyderpora",
    district: "Srinagar",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "Cluster University Srinagar",
    forGirls: 0,
  },
  {
    name: "Govternment Degree College Beerwah",
    district: "Budgam",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Hamidi Kashmiri Memorial Government Degree College Eidgah Kashmir",
    district: "Srinagar",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2019,
    universityName: "Cluster University Srinagar",
    forGirls: 0,
  },
  {
    name: "Hassan Khoyihami Memorial Degree College Bandipora",
    district: "Bandipora",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Institute of Advanced Studies in Education Srinagar",
    district: "Srinagar",
    location: "Urban",
    collegeType: "Constituent / University College",
    management: "State Government",
    yearOfEstablishment: 1937,
    universityName: "Cluster University Srinagar",
    forGirls: 0,
  },
  {
    name: "Islamia College of Science & Commerce, Srinagar",
    district: "Srinagar",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1961,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Jammu and Kashmir Institute of Mathematical Sciences",
    district: "Srinagar",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "Central Government",
    yearOfEstablishment: 2013,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 0,
  },
  {
    name: "Pt Premnath Dogra GDC Samba",
    district: "Samba",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2005,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Shri Kishan Chander Government Degree College Poonch",
    district: "Poonch",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 1955,
    universityName: "University of Jammu, Jammu Tawi",
    forGirls: 0,
  },
  {
    name: "Sri Pratap College Srinagar",
    district: "Srinagar",
    location: "Urban",
    collegeType: "Constituent / University College",
    management: "State Government",
    yearOfEstablishment: 1905,
    universityName: "Cluster University Srinagar",
    forGirls: 0,
  },
  {
    name: "Srinagar Women's College Zakura",
    district: "Srinagar",
    location: "Urban",
    collegeType: "Affiliated College",
    management: "State Government",
    yearOfEstablishment: 2008,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 1,
  },
  {
    name: "Vishwa Bharti Women's College Rainawari, Srinagar",
    district: "Jammu",
    location: "Rural",
    collegeType: "Affiliated College",
    management: "Local Body",
    yearOfEstablishment: 1979,
    universityName: "University of Kashmir, Srinagar",
    forGirls: 1,
  },
];

// 7 roadmap templates
const ROADMAPS = [
  {
    id: 1,
    title: "Arts & Humanities Roadmap",
    semester:
      '{"year1":["Foundation courses","Language skills"],"year2":["Specialization","Research methods"],"year3":["Advanced studies","Thesis"]}',
    internships: '["Museums","Publishing houses","NGOs"]',
    exams: '["NET","GATE"]',
    certifications: '["Language certifications"]',
    upscaling: '["Foreign language","Digital humanities"]',
  },
  {
    id: 2,
    title: "Science & Research Roadmap",
    semester:
      '{"year1":["Basic sciences","Lab techniques"],"year2":["Advanced courses","Research projects"],"year3":["Thesis","Publications"]}',
    internships: '["Research labs","Universities","ISRO"]',
    exams: '["CSIR-NET","GATE","JAM"]',
    certifications: '["Lab safety","Research ethics"]',
    upscaling: '["Data analysis","Publication skills"]',
  },
  {
    id: 3,
    title: "Commerce & Business Roadmap",
    semester:
      '{"year1":["Accounting basics","Business law"],"year2":["Finance","Marketing"],"year3":["Specialization","Internships"]}',
    internships: '["Banks","Consulting firms","Startups"]',
    exams: '["CA","CMA","CS"]',
    certifications: '["CFA","Financial modeling"]',
    upscaling: '["Data analytics","Leadership"]',
  },
  {
    id: 4,
    title: "IT & Computing Roadmap",
    semester:
      '{"year1":["Programming basics","Data structures"],"year2":["Web dev","Databases"],"year3":["AI/ML","Cloud computing"]}',
    internships: '["Tech companies","Startups","Research labs"]',
    exams: '["GATE"]',
    certifications: '["AWS","Google Cloud","Azure"]',
    upscaling: '["System design","Open source"]',
  },
  {
    id: 5,
    title: "Professional Services Roadmap",
    semester:
      '{"year1":["Foundation courses","Communication"],"year2":["Technical skills","Practicum"],"year3":["Specialization","Licensing prep"]}',
    internships: '["Hospitals","Law firms","Clinics"]',
    exams: '["Bar exam","NEET PG","UPSC"]',
    certifications: '["Professional licenses"]',
    upscaling: '["Continuing education","Specialization"]',
  },
  {
    id: 6,
    title: "Entrepreneurship Roadmap",
    semester:
      '{"year1":["Business basics","Market research"],"year2":["Product development","Finance"],"year3":["Launch","Scaling"]}',
    internships: '["Startups","Incubators","VCs"]',
    exams: "[]",
    certifications: '["Project management","Lean startup"]',
    upscaling: '["Pitching","Networking","Fundraising"]',
  },
  {
    id: 7,
    title: "Engineering Roadmap",
    semester:
      '{"year1":["Math foundations","Physics"],"year2":["Core engineering","Projects"],"year3":["Specialization","Industry training"]}',
    internships: '["Engineering firms","Manufacturing","R&D labs"]',
    exams: '["GATE","GRE"]',
    certifications: '["AutoCAD","SolidWorks"]',
    upscaling: '["Management","Industry 4.0"]',
  },
];

/**
 * COMPLETE seeding: Create tables, clear, insert ALL data
 * Includes: careers, colleges, roadmaps, courses, career_course, course_college
 */
export async function seedDatabase() {
  console.log("🌱 SEEDING DATABASE WITH ALL DATA...");

  try {
    // 1. CREATE ALL TABLES
    console.log("📋 Step 1: Creating all tables...");
    await db.run(
      sql`CREATE TABLE IF NOT EXISTS careers (id INTEGER PRIMARY KEY AUTOINCREMENT, career_name TEXT NOT NULL, r REAL, i REAL, a REAL, s REAL, e REAL, c REAL, description TEXT)`
    );
    await db.run(
      sql`CREATE TABLE IF NOT EXISTS college_list (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, district TEXT, location TEXT, college_type TEXT, management TEXT, year_of_establishment INTEGER, university_name TEXT, for_girls INTEGER DEFAULT 0)`
    );
    await db.run(
      sql`CREATE TABLE IF NOT EXISTS roadmap_templates (id INTEGER PRIMARY KEY, title TEXT NOT NULL, semester TEXT, internships TEXT, exams TEXT, certifications TEXT, upscaling TEXT)`
    );
    await db.run(
      sql`CREATE TABLE IF NOT EXISTS courses (id INTEGER PRIMARY KEY, course_name TEXT NOT NULL, roadmap_id INTEGER, stream TEXT)`
    );
    await db.run(
      sql`CREATE TABLE IF NOT EXISTS career_course (id INTEGER PRIMARY KEY, career_name TEXT NOT NULL, course_name TEXT NOT NULL)`
    );
    await db.run(
      sql`CREATE TABLE IF NOT EXISTS course_college (id INTEGER PRIMARY KEY, course_name TEXT NOT NULL, college_name TEXT NOT NULL)`
    );
    console.log("✅ All tables created!");

    // 2. CLEAR OLD DATA
    console.log("🗑️ Step 2: Clearing old data...");
    await db.run(sql`DELETE FROM career_course`);
    await db.run(sql`DELETE FROM course_college`);
    await db.run(sql`DELETE FROM courses`);
    await db.run(sql`DELETE FROM careers`);
    await db.run(sql`DELETE FROM college_list`);
    await db.run(sql`DELETE FROM roadmap_templates`);
    console.log("✅ Old data cleared!");

    // 3. SEED CAREERS (132)
    console.log("💼 Step 3: Seeding careers...");
    for (const c of RIASEC_CAREERS) {
      await db.run(
        sql`INSERT INTO careers (career_name, r, i, a, s, e, c, description) VALUES (${c.Title}, ${c.Realistic}, ${c.Investigative}, ${c.Artistic}, ${c.Social}, ${c.Enterprising}, ${c.Conventional}, ${c.desc})`
      );
    }
    console.log(`✅ Inserted ${RIASEC_CAREERS.length} careers!`);

    // 4. SEED COLLEGES (136)
    console.log("🏫 Step 4: Seeding colleges...");
    for (const c of COLLEGES) {
      await db.run(
        sql`INSERT INTO college_list (name, district, location, college_type, management, year_of_establishment, university_name, for_girls) VALUES (${c.name}, ${c.district}, ${c.location}, ${c.collegeType}, ${c.management}, ${c.yearOfEstablishment}, ${c.universityName}, ${c.forGirls})`
      );
    }
    console.log(`✅ Inserted ${COLLEGES.length} colleges!`);

    // 5. SEED ROADMAPS (7)
    console.log("🗺️ Step 5: Seeding roadmaps...");
    for (const r of ROADMAPS) {
      await db.run(
        sql`INSERT INTO roadmap_templates (id, title, semester, internships, exams, certifications, upscaling) VALUES (${r.id}, ${r.title}, ${r.semester}, ${r.internships}, ${r.exams}, ${r.certifications}, ${r.upscaling})`
      );
    }
    console.log(`✅ Inserted ${ROADMAPS.length} roadmaps!`);

    // 6. SEED COURSES (215)
    console.log("📚 Step 6: Seeding courses...");
    for (const c of COURSES_DATA) {
      await db.run(
        sql`INSERT INTO courses (id, course_name, roadmap_id, stream) VALUES (${c.id}, ${c.name}, ${c.roadmapId}, ${c.stream})`
      );
    }
    console.log(`✅ Inserted ${COURSES_DATA.length} courses!`);

    // 7. SEED CAREER-COURSE RELATIONS (2412)
    console.log(
      "🔗 Step 7: Seeding career-course relations (this may take a moment)..."
    );
    for (const cc of CAREER_COURSE_DATA) {
      await db.run(
        sql`INSERT INTO career_course (id, career_name, course_name) VALUES (${cc.id}, ${cc.career}, ${cc.course})`
      );
    }
    console.log(
      `✅ Inserted ${CAREER_COURSE_DATA.length} career-course relations!`
    );

    // 8. SEED COURSE-COLLEGE RELATIONS (1699)
    console.log(
      "🔗 Step 8: Seeding course-college relations (this may take a moment)..."
    );
    for (const cc of COURSE_COLLEGE_DATA) {
      await db.run(
        sql`INSERT INTO course_college (id, course_name, college_name) VALUES (${cc.id}, ${cc.course}, ${cc.college})`
      );
    }
    console.log(
      `✅ Inserted ${COURSE_COLLEGE_DATA.length} course-college relations!`
    );

    console.log("🎉 DATABASE SEEDING COMPLETE!");
    console.log(
      `📊 TOTAL: ${RIASEC_CAREERS.length} careers, ${COLLEGES.length} colleges, ${ROADMAPS.length} roadmaps, ${COURSES_DATA.length} courses, ${CAREER_COURSE_DATA.length} career-course, ${COURSE_COLLEGE_DATA.length} course-college`
    );
  } catch (error) {
    console.error("❌ SEEDING ERROR:", error);
    throw error;
  }
}
