


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."roles_auth" AS ENUM (
    'STUDENT',
    'PARENT',
    'COLLEGE'
);


ALTER TYPE "public"."roles_auth" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."CareerToCourse" (
    "id" bigint NOT NULL,
    "careers" "text",
    "courses" "text"
);


ALTER TABLE "public"."CareerToCourse" OWNER TO "postgres";


COMMENT ON TABLE "public"."CareerToCourse" IS 'Career → Course junction';



CREATE TABLE IF NOT EXISTS "public"."CollegeFacilities" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "college_name" "text" NOT NULL,
    "has_library" boolean DEFAULT false,
    "has_hostel" boolean DEFAULT false,
    "has_cafeteria" boolean DEFAULT false,
    "has_sports_ground" boolean DEFAULT false,
    "has_gym" boolean DEFAULT false,
    "has_medical_facility" boolean DEFAULT false,
    "has_wifi" boolean DEFAULT false,
    "has_computer_lab" boolean DEFAULT false,
    "has_auditorium" boolean DEFAULT false,
    "has_parking" boolean DEFAULT false,
    "hostel_capacity" integer,
    "annual_fees_general" numeric(10,2),
    "annual_fees_ews" numeric(10,2),
    "hostel_fees" numeric(10,2),
    "scholarship_available" boolean DEFAULT false,
    "scholarship_amount" numeric(10,2)
);


ALTER TABLE "public"."CollegeFacilities" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."CollegeList" (
    "Aishe Code" "text" NOT NULL,
    "Name" "text" NOT NULL,
    "District" "text",
    "State" "text",
    "Website" "text",
    "Year Of Establishment" bigint,
    "Location" "text",
    "College Type" "text",
    "Manegement" "text",
    "University Aishe Code" "text",
    "University Name" "text",
    "University Type" "text",
    "For_girls" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."CollegeList" OWNER TO "postgres";


COMMENT ON TABLE "public"."CollegeList" IS 'Master college data (pre-seeded from CSV)';



COMMENT ON COLUMN "public"."CollegeList"."For_girls" IS 'Boolean value if a college is only for girls';



CREATE TABLE IF NOT EXISTS "public"."CollegeProfiles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "college_name" "text" NOT NULL,
    "aishe_code" "text",
    "contact_name" "text",
    "designation" "text",
    "contact_email" "text",
    "contact_phone" "text",
    "is_verified" boolean DEFAULT false,
    "verification_document_url" "text",
    "is_profile_complete" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."CollegeProfiles" OWNER TO "postgres";


COMMENT ON TABLE "public"."CollegeProfiles" IS 'College info, verification & contact details';



CREATE TABLE IF NOT EXISTS "public"."CourseToCollege" (
    "id" bigint NOT NULL,
    "courses" "text",
    "colleges" "text"
);


ALTER TABLE "public"."CourseToCollege" OWNER TO "postgres";


COMMENT ON TABLE "public"."CourseToCollege" IS 'Course → College junction';



CREATE TABLE IF NOT EXISTS "public"."Courses" (
    "id" bigint NOT NULL,
    "Courses" "text" NOT NULL,
    "roadmap_id" bigint,
    "stream" "text"
);


ALTER TABLE "public"."Courses" OWNER TO "postgres";


COMMENT ON TABLE "public"."Courses" IS 'Course master data';



COMMENT ON COLUMN "public"."Courses"."roadmap_id" IS 'The id of the roadmap template suitable for each course';



COMMENT ON COLUMN "public"."Courses"."stream" IS 'Art / Science / Commerce';



ALTER TABLE "public"."Courses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Courses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Notifications" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "type" "text" NOT NULL,
    "title" "text" NOT NULL,
    "message" "text",
    "metadata" "jsonb",
    "read" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."Notifications" OWNER TO "postgres";


COMMENT ON TABLE "public"."Notifications" IS 'In-app notification system';



CREATE TABLE IF NOT EXISTS "public"."ParentProfiles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "full_name" "text",
    "phone" "text",
    "relationship" "text",
    "city" "text",
    "state" "text",
    "is_profile_complete" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "awareness_quiz" "jsonb",
    CONSTRAINT "ParentProfiles_relationship_check" CHECK (("relationship" = ANY (ARRAY['Father'::"text", 'Mother'::"text", 'Guardian'::"text", 'Other'::"text"])))
);


ALTER TABLE "public"."ParentProfiles" OWNER TO "postgres";


COMMENT ON TABLE "public"."ParentProfiles" IS 'Parent personal info & relationship details';



CREATE TABLE IF NOT EXISTS "public"."ParentStudentLinks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "parent_id" "uuid" NOT NULL,
    "student_id" "uuid" NOT NULL,
    "status" "text" DEFAULT 'PENDING'::"text",
    "requested_at" timestamp with time zone DEFAULT "now"(),
    "responded_at" timestamp with time zone,
    "accepted_at" timestamp with time zone,
    CONSTRAINT "ParentStudentLinks_status_check" CHECK (("status" = ANY (ARRAY['PENDING'::"text", 'ACCEPTED'::"text", 'REJECTED'::"text", 'REVOKED'::"text"])))
);


ALTER TABLE "public"."ParentStudentLinks" OWNER TO "postgres";


COMMENT ON TABLE "public"."ParentStudentLinks" IS 'Parent-student linking (invite code system)';



CREATE TABLE IF NOT EXISTS "public"."QuizResults" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "score_logical" double precision DEFAULT 0,
    "score_quant" double precision DEFAULT 0,
    "score_analytical" double precision DEFAULT 0,
    "score_verbal" double precision DEFAULT 0,
    "score_spatial" double precision DEFAULT 0,
    "score_creativity" double precision DEFAULT 0,
    "score_entrepreneurial" double precision DEFAULT 0,
    "riasec_realistic" double precision DEFAULT 0,
    "riasec_investigative" double precision DEFAULT 0,
    "riasec_artistic" double precision DEFAULT 0,
    "riasec_social" double precision DEFAULT 0,
    "riasec_enterprising" double precision DEFAULT 0,
    "riasec_conventional" double precision DEFAULT 0,
    "answers" "jsonb",
    "is_complete" boolean DEFAULT false,
    "completed_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."QuizResults" OWNER TO "postgres";


COMMENT ON TABLE "public"."QuizResults" IS '7-dimension aptitude + 6-dimension RIASEC scores';



CREATE TABLE IF NOT EXISTS "public"."RIASEC" (
    "Title" "text" NOT NULL,
    "Realistic" double precision,
    "Investigative" double precision,
    "Artistic" double precision,
    "Social" double precision,
    "Enterprising" double precision,
    "Conventional" double precision,
    "desc" "text"
);


ALTER TABLE "public"."RIASEC" OWNER TO "postgres";


COMMENT ON TABLE "public"."RIASEC" IS 'Career-RIASEC mapping weights';



COMMENT ON COLUMN "public"."RIASEC"."desc" IS 'One liner for every career';



CREATE TABLE IF NOT EXISTS "public"."Recommendations" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "quiz_result_id" "uuid",
    "top_careers" "text"[],
    "career_explanations" "jsonb",
    "career_courses" "jsonb",
    "recommended_colleges" "jsonb",
    "college_explanations" "jsonb",
    "riasec_scores" double precision[],
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."Recommendations" OWNER TO "postgres";


COMMENT ON TABLE "public"."Recommendations" IS 'Career & college recommendations with explanations';



CREATE TABLE IF NOT EXISTS "public"."RoadmapTemplates" (
    "id" bigint NOT NULL,
    "title" "text",
    "semester" json,
    "internships" json,
    "exams" json,
    "certifications" json,
    "upscaling" json
);


ALTER TABLE "public"."RoadmapTemplates" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Scholarship" (
    "Scheme" "text",
    "Eligibility" "text",
    "Benefit" "text",
    "Link" "text",
    "id" bigint NOT NULL
);


ALTER TABLE "public"."Scholarship" OWNER TO "postgres";


ALTER TABLE "public"."Scholarship" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Scholarship_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Schools Data" (
    "district" "text",
    "school_name" "text",
    "school_type" "text",
    "longitude" double precision,
    "latitude" double precision,
    "id" bigint NOT NULL
);


ALTER TABLE "public"."Schools Data" OWNER TO "postgres";


ALTER TABLE "public"."Schools Data" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Schools Data_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."StudentProfiles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "full_name" "text",
    "gender" "text",
    "date_of_birth" "date",
    "phone" "text",
    "locality" "text",
    "district" "text",
    "state" "text",
    "category" "text",
    "grade" "text",
    "board" "text",
    "school_name" "text",
    "budget" integer DEFAULT 100000,
    "extracurriculars" "text"[],
    "hobbies" "text"[],
    "importance_locality" integer DEFAULT 3,
    "importance_financial" integer DEFAULT 3,
    "importance_eligibility" integer DEFAULT 3,
    "importance_events_hobbies" integer DEFAULT 3,
    "importance_quality" integer DEFAULT 3,
    "is_profile_complete" boolean DEFAULT false,
    "onboarding_step" integer DEFAULT 0,
    "invite_code" "text",
    "invite_code_expires_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "StudentProfiles_category_check" CHECK (("category" = ANY (ARRAY['General'::"text", 'OBC'::"text", 'SC'::"text", 'ST'::"text", 'EWS'::"text"]))),
    CONSTRAINT "StudentProfiles_gender_check" CHECK (("gender" = ANY (ARRAY['Male'::"text", 'Female'::"text", 'Other'::"text"]))),
    CONSTRAINT "StudentProfiles_importance_eligibility_check" CHECK ((("importance_eligibility" >= 0) AND ("importance_eligibility" <= 5))),
    CONSTRAINT "StudentProfiles_importance_events_hobbies_check" CHECK ((("importance_events_hobbies" >= 0) AND ("importance_events_hobbies" <= 5))),
    CONSTRAINT "StudentProfiles_importance_financial_check" CHECK ((("importance_financial" >= 0) AND ("importance_financial" <= 5))),
    CONSTRAINT "StudentProfiles_importance_locality_check" CHECK ((("importance_locality" >= 0) AND ("importance_locality" <= 5))),
    CONSTRAINT "StudentProfiles_importance_quality_check" CHECK ((("importance_quality" >= 0) AND ("importance_quality" <= 5)))
);


ALTER TABLE "public"."StudentProfiles" OWNER TO "postgres";


COMMENT ON TABLE "public"."StudentProfiles" IS 'Student academic, personal & preference data';



CREATE TABLE IF NOT EXISTS "public"."StudyMaterials" (
    "courses" "text",
    "link" "text",
    "duration" "text",
    "materials" "text"
);


ALTER TABLE "public"."StudyMaterials" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Users" (
    "u_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "email" "text" NOT NULL,
    "role" "text" DEFAULT 'STUDENT'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "Users_role_check" CHECK (("role" = ANY (ARRAY['STUDENT'::"text", 'PARENT'::"text", 'COLLEGE'::"text"])))
);


ALTER TABLE "public"."Users" OWNER TO "postgres";


COMMENT ON TABLE "public"."Users" IS 'Core user table with roles (STUDENT / PARENT / COLLEGE)';



CREATE TABLE IF NOT EXISTS "public"."career_comparison" (
    "Careers" "text",
    "Salary (5 Yrs Exp in INR)" "text",
    "Growth Rate (10 yrs)" "text",
    "Market Demand Score (1-10)" bigint,
    "Job Stability Score (1-10)" bigint
);


ALTER TABLE "public"."career_comparison" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."career_roadmaps_new" (
    "Courses" "text",
    "Industry" "text",
    "Government Exams" "text",
    "Company names" "text",
    "Higher Education" "text",
    "id" bigint NOT NULL
);


ALTER TABLE "public"."career_roadmaps_new" OWNER TO "postgres";


COMMENT ON TABLE "public"."career_roadmaps_new" IS 'Personalised Career Roadmaps';



ALTER TABLE "public"."career_roadmaps_new" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."career_roadmaps_new_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."CareerToCourse" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."career_to_course_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."comment_votes" (
    "id" integer NOT NULL,
    "comment_id" integer NOT NULL,
    "user_id" character varying(255) NOT NULL,
    "value" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "comment_votes_value_check" CHECK (("value" = ANY (ARRAY[1, '-1'::integer])))
);


ALTER TABLE "public"."comment_votes" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."comment_votes_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."comment_votes_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."comment_votes_id_seq" OWNED BY "public"."comment_votes"."id";



CREATE TABLE IF NOT EXISTS "public"."comments" (
    "id" integer NOT NULL,
    "discussion_id" integer NOT NULL,
    "user_id" character varying(255) NOT NULL,
    "content" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."comments" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."comments_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."comments_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."comments_id_seq" OWNED BY "public"."comments"."id";



ALTER TABLE "public"."CourseToCollege" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."course_to_college_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."discussion_tags" (
    "id" integer NOT NULL,
    "discussion_id" integer NOT NULL,
    "tag_id" integer NOT NULL
);


ALTER TABLE "public"."discussion_tags" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."discussion_tags_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."discussion_tags_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."discussion_tags_id_seq" OWNED BY "public"."discussion_tags"."id";



CREATE TABLE IF NOT EXISTS "public"."discussion_votes" (
    "id" integer NOT NULL,
    "discussion_id" integer NOT NULL,
    "user_id" character varying(255) NOT NULL,
    "value" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "discussion_votes_value_check" CHECK (("value" = ANY (ARRAY[1, '-1'::integer])))
);


ALTER TABLE "public"."discussion_votes" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."discussion_votes_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."discussion_votes_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."discussion_votes_id_seq" OWNED BY "public"."discussion_votes"."id";



CREATE TABLE IF NOT EXISTS "public"."discussions" (
    "id" integer NOT NULL,
    "title" character varying(255) NOT NULL,
    "content" "text" NOT NULL,
    "user_id" character varying(255) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."discussions" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."discussions_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."discussions_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."discussions_id_seq" OWNED BY "public"."discussions"."id";



ALTER TABLE "public"."RoadmapTemplates" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."roadmap_templates_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" integer NOT NULL,
    "name" character varying(50) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."tags" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."tags_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."tags_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."tags_id_seq" OWNED BY "public"."tags"."id";



ALTER TABLE ONLY "public"."comment_votes" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."comment_votes_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."comments" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."comments_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."discussion_tags" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."discussion_tags_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."discussion_votes" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."discussion_votes_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."discussions" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."discussions_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."tags" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."tags_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."CollegeFacilities"
    ADD CONSTRAINT "CollegeFacilities_college_name_key" UNIQUE ("college_name");



ALTER TABLE ONLY "public"."CollegeFacilities"
    ADD CONSTRAINT "CollegeFacilities_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."CollegeList"
    ADD CONSTRAINT "CollegeList_Name_key" UNIQUE ("Name");



ALTER TABLE ONLY "public"."CollegeList"
    ADD CONSTRAINT "CollegeList_pkey" PRIMARY KEY ("Name");



ALTER TABLE ONLY "public"."CollegeProfiles"
    ADD CONSTRAINT "CollegeProfiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."CollegeProfiles"
    ADD CONSTRAINT "CollegeProfiles_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."Courses"
    ADD CONSTRAINT "Courses_Course_key" UNIQUE ("Courses");



ALTER TABLE ONLY "public"."Courses"
    ADD CONSTRAINT "Courses_pkey" PRIMARY KEY ("id", "Courses");



ALTER TABLE ONLY "public"."Notifications"
    ADD CONSTRAINT "Notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ParentProfiles"
    ADD CONSTRAINT "ParentProfiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ParentProfiles"
    ADD CONSTRAINT "ParentProfiles_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."ParentStudentLinks"
    ADD CONSTRAINT "ParentStudentLinks_parent_id_student_id_key" UNIQUE ("parent_id", "student_id");



ALTER TABLE ONLY "public"."ParentStudentLinks"
    ADD CONSTRAINT "ParentStudentLinks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."QuizResults"
    ADD CONSTRAINT "QuizResults_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."RIASEC"
    ADD CONSTRAINT "RIASEC_pkey" PRIMARY KEY ("Title");



ALTER TABLE ONLY "public"."Recommendations"
    ADD CONSTRAINT "Recommendations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Scholarship"
    ADD CONSTRAINT "Scholarship_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."Scholarship"
    ADD CONSTRAINT "Scholarship_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Schools Data"
    ADD CONSTRAINT "Schools Data_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."Schools Data"
    ADD CONSTRAINT "Schools Data_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."StudentProfiles"
    ADD CONSTRAINT "StudentProfiles_invite_code_key" UNIQUE ("invite_code");



ALTER TABLE ONLY "public"."StudentProfiles"
    ADD CONSTRAINT "StudentProfiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."StudentProfiles"
    ADD CONSTRAINT "StudentProfiles_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("u_id");



ALTER TABLE ONLY "public"."career_roadmaps_new"
    ADD CONSTRAINT "career_roadmaps_new_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."career_roadmaps_new"
    ADD CONSTRAINT "career_roadmaps_new_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."comment_votes"
    ADD CONSTRAINT "comment_votes_comment_id_user_id_key" UNIQUE ("comment_id", "user_id");



ALTER TABLE ONLY "public"."comment_votes"
    ADD CONSTRAINT "comment_votes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."comments"
    ADD CONSTRAINT "comments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."CourseToCollege"
    ADD CONSTRAINT "course_to_college_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."discussion_tags"
    ADD CONSTRAINT "discussion_tags_discussion_id_tag_id_key" UNIQUE ("discussion_id", "tag_id");



ALTER TABLE ONLY "public"."discussion_tags"
    ADD CONSTRAINT "discussion_tags_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."discussion_votes"
    ADD CONSTRAINT "discussion_votes_discussion_id_user_id_key" UNIQUE ("discussion_id", "user_id");



ALTER TABLE ONLY "public"."discussion_votes"
    ADD CONSTRAINT "discussion_votes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."discussions"
    ADD CONSTRAINT "discussions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."RoadmapTemplates"
    ADD CONSTRAINT "roadmap_templates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_college_profiles_user" ON "public"."CollegeProfiles" USING "btree" ("user_id");



CREATE INDEX "idx_comment_votes_comment_id" ON "public"."comment_votes" USING "btree" ("comment_id");



CREATE INDEX "idx_comments_discussion_id" ON "public"."comments" USING "btree" ("discussion_id");



CREATE INDEX "idx_discussion_votes_discussion_id" ON "public"."discussion_votes" USING "btree" ("discussion_id");



CREATE INDEX "idx_notifications_read" ON "public"."Notifications" USING "btree" ("read");



CREATE INDEX "idx_notifications_user" ON "public"."Notifications" USING "btree" ("user_id");



CREATE INDEX "idx_parent_links_parent" ON "public"."ParentStudentLinks" USING "btree" ("parent_id");



CREATE INDEX "idx_parent_links_status" ON "public"."ParentStudentLinks" USING "btree" ("status");



CREATE INDEX "idx_parent_links_student" ON "public"."ParentStudentLinks" USING "btree" ("student_id");



CREATE INDEX "idx_parent_profiles_user" ON "public"."ParentProfiles" USING "btree" ("user_id");



CREATE INDEX "idx_quiz_results_complete" ON "public"."QuizResults" USING "btree" ("is_complete");



CREATE INDEX "idx_quiz_results_user" ON "public"."QuizResults" USING "btree" ("user_id");



CREATE INDEX "idx_recommendations_quiz" ON "public"."Recommendations" USING "btree" ("quiz_result_id");



CREATE INDEX "idx_recommendations_user" ON "public"."Recommendations" USING "btree" ("user_id");



CREATE INDEX "idx_student_profiles_invite" ON "public"."StudentProfiles" USING "btree" ("invite_code");



CREATE INDEX "idx_student_profiles_user" ON "public"."StudentProfiles" USING "btree" ("user_id");



CREATE INDEX "idx_users_email" ON "public"."Users" USING "btree" ("email");



CREATE INDEX "idx_users_role" ON "public"."Users" USING "btree" ("role");



ALTER TABLE ONLY "public"."CollegeFacilities"
    ADD CONSTRAINT "CollegeFacilities_college_name_fkey" FOREIGN KEY ("college_name") REFERENCES "public"."CollegeList"("Name");



ALTER TABLE ONLY "public"."CollegeProfiles"
    ADD CONSTRAINT "CollegeProfiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."Users"("u_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Courses"
    ADD CONSTRAINT "Courses_roadmap_id_fkey" FOREIGN KEY ("roadmap_id") REFERENCES "public"."RoadmapTemplates"("id");



ALTER TABLE ONLY "public"."Notifications"
    ADD CONSTRAINT "Notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."Users"("u_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ParentProfiles"
    ADD CONSTRAINT "ParentProfiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."Users"("u_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ParentStudentLinks"
    ADD CONSTRAINT "ParentStudentLinks_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."ParentProfiles"("user_id");



ALTER TABLE ONLY "public"."ParentStudentLinks"
    ADD CONSTRAINT "ParentStudentLinks_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."StudentProfiles"("user_id");



ALTER TABLE ONLY "public"."QuizResults"
    ADD CONSTRAINT "QuizResults_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."StudentProfiles"("user_id");



ALTER TABLE ONLY "public"."Recommendations"
    ADD CONSTRAINT "Recommendations_quiz_result_id_fkey" FOREIGN KEY ("quiz_result_id") REFERENCES "public"."QuizResults"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Recommendations"
    ADD CONSTRAINT "Recommendations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."StudentProfiles"("user_id");



ALTER TABLE ONLY "public"."StudentProfiles"
    ADD CONSTRAINT "StudentProfiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."Users"("u_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."CareerToCourse"
    ADD CONSTRAINT "career_to_course_careers_fkey" FOREIGN KEY ("careers") REFERENCES "public"."RIASEC"("Title");



ALTER TABLE ONLY "public"."CareerToCourse"
    ADD CONSTRAINT "career_to_course_courses_fkey" FOREIGN KEY ("courses") REFERENCES "public"."Courses"("Courses");



ALTER TABLE ONLY "public"."comment_votes"
    ADD CONSTRAINT "comment_votes_comment_id_fkey" FOREIGN KEY ("comment_id") REFERENCES "public"."comments"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."comments"
    ADD CONSTRAINT "comments_discussion_id_fkey" FOREIGN KEY ("discussion_id") REFERENCES "public"."discussions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."CourseToCollege"
    ADD CONSTRAINT "course_to_college_colleges_fkey" FOREIGN KEY ("colleges") REFERENCES "public"."CollegeList"("Name");



ALTER TABLE ONLY "public"."CourseToCollege"
    ADD CONSTRAINT "course_to_college_courses_fkey" FOREIGN KEY ("courses") REFERENCES "public"."Courses"("Courses");



ALTER TABLE ONLY "public"."discussion_tags"
    ADD CONSTRAINT "discussion_tags_discussion_id_fkey" FOREIGN KEY ("discussion_id") REFERENCES "public"."discussions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."discussion_tags"
    ADD CONSTRAINT "discussion_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."discussion_votes"
    ADD CONSTRAINT "discussion_votes_discussion_id_fkey" FOREIGN KEY ("discussion_id") REFERENCES "public"."discussions"("id") ON DELETE CASCADE;





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."CareerToCourse" TO "anon";
GRANT ALL ON TABLE "public"."CareerToCourse" TO "authenticated";
GRANT ALL ON TABLE "public"."CareerToCourse" TO "service_role";



GRANT ALL ON TABLE "public"."CollegeFacilities" TO "anon";
GRANT ALL ON TABLE "public"."CollegeFacilities" TO "authenticated";
GRANT ALL ON TABLE "public"."CollegeFacilities" TO "service_role";



GRANT ALL ON TABLE "public"."CollegeList" TO "anon";
GRANT ALL ON TABLE "public"."CollegeList" TO "authenticated";
GRANT ALL ON TABLE "public"."CollegeList" TO "service_role";



GRANT ALL ON TABLE "public"."CollegeProfiles" TO "anon";
GRANT ALL ON TABLE "public"."CollegeProfiles" TO "authenticated";
GRANT ALL ON TABLE "public"."CollegeProfiles" TO "service_role";



GRANT ALL ON TABLE "public"."CourseToCollege" TO "anon";
GRANT ALL ON TABLE "public"."CourseToCollege" TO "authenticated";
GRANT ALL ON TABLE "public"."CourseToCollege" TO "service_role";



GRANT ALL ON TABLE "public"."Courses" TO "anon";
GRANT ALL ON TABLE "public"."Courses" TO "authenticated";
GRANT ALL ON TABLE "public"."Courses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Courses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Courses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Courses_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Notifications" TO "anon";
GRANT ALL ON TABLE "public"."Notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."Notifications" TO "service_role";



GRANT ALL ON TABLE "public"."ParentProfiles" TO "anon";
GRANT ALL ON TABLE "public"."ParentProfiles" TO "authenticated";
GRANT ALL ON TABLE "public"."ParentProfiles" TO "service_role";



GRANT ALL ON TABLE "public"."ParentStudentLinks" TO "anon";
GRANT ALL ON TABLE "public"."ParentStudentLinks" TO "authenticated";
GRANT ALL ON TABLE "public"."ParentStudentLinks" TO "service_role";



GRANT ALL ON TABLE "public"."QuizResults" TO "anon";
GRANT ALL ON TABLE "public"."QuizResults" TO "authenticated";
GRANT ALL ON TABLE "public"."QuizResults" TO "service_role";



GRANT ALL ON TABLE "public"."RIASEC" TO "anon";
GRANT ALL ON TABLE "public"."RIASEC" TO "authenticated";
GRANT ALL ON TABLE "public"."RIASEC" TO "service_role";



GRANT ALL ON TABLE "public"."Recommendations" TO "anon";
GRANT ALL ON TABLE "public"."Recommendations" TO "authenticated";
GRANT ALL ON TABLE "public"."Recommendations" TO "service_role";



GRANT ALL ON TABLE "public"."RoadmapTemplates" TO "anon";
GRANT ALL ON TABLE "public"."RoadmapTemplates" TO "authenticated";
GRANT ALL ON TABLE "public"."RoadmapTemplates" TO "service_role";



GRANT ALL ON TABLE "public"."Scholarship" TO "anon";
GRANT ALL ON TABLE "public"."Scholarship" TO "authenticated";
GRANT ALL ON TABLE "public"."Scholarship" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Scholarship_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Scholarship_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Scholarship_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Schools Data" TO "anon";
GRANT ALL ON TABLE "public"."Schools Data" TO "authenticated";
GRANT ALL ON TABLE "public"."Schools Data" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Schools Data_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Schools Data_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Schools Data_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."StudentProfiles" TO "anon";
GRANT ALL ON TABLE "public"."StudentProfiles" TO "authenticated";
GRANT ALL ON TABLE "public"."StudentProfiles" TO "service_role";



GRANT ALL ON TABLE "public"."StudyMaterials" TO "anon";
GRANT ALL ON TABLE "public"."StudyMaterials" TO "authenticated";
GRANT ALL ON TABLE "public"."StudyMaterials" TO "service_role";



GRANT ALL ON TABLE "public"."Users" TO "anon";
GRANT ALL ON TABLE "public"."Users" TO "authenticated";
GRANT ALL ON TABLE "public"."Users" TO "service_role";



GRANT ALL ON TABLE "public"."career_comparison" TO "anon";
GRANT ALL ON TABLE "public"."career_comparison" TO "authenticated";
GRANT ALL ON TABLE "public"."career_comparison" TO "service_role";



GRANT ALL ON TABLE "public"."career_roadmaps_new" TO "anon";
GRANT ALL ON TABLE "public"."career_roadmaps_new" TO "authenticated";
GRANT ALL ON TABLE "public"."career_roadmaps_new" TO "service_role";



GRANT ALL ON SEQUENCE "public"."career_roadmaps_new_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."career_roadmaps_new_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."career_roadmaps_new_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."career_to_course_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."career_to_course_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."career_to_course_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."comment_votes" TO "anon";
GRANT ALL ON TABLE "public"."comment_votes" TO "authenticated";
GRANT ALL ON TABLE "public"."comment_votes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."comment_votes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."comment_votes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."comment_votes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."comments" TO "anon";
GRANT ALL ON TABLE "public"."comments" TO "authenticated";
GRANT ALL ON TABLE "public"."comments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."comments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."comments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."comments_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."course_to_college_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."course_to_college_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."course_to_college_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."discussion_tags" TO "anon";
GRANT ALL ON TABLE "public"."discussion_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."discussion_tags" TO "service_role";



GRANT ALL ON SEQUENCE "public"."discussion_tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."discussion_tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."discussion_tags_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."discussion_votes" TO "anon";
GRANT ALL ON TABLE "public"."discussion_votes" TO "authenticated";
GRANT ALL ON TABLE "public"."discussion_votes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."discussion_votes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."discussion_votes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."discussion_votes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."discussions" TO "anon";
GRANT ALL ON TABLE "public"."discussions" TO "authenticated";
GRANT ALL ON TABLE "public"."discussions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."discussions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."discussions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."discussions_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."roadmap_templates_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."roadmap_templates_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."roadmap_templates_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































